### ISSUE TITLE
Default timeout option

### ISSUE THREAD

**Issue by uradox** [Daltron/NotificationBanner#100]
Hi,

I feel that for some things the amount of time the banner is displayed is slightly too long. It would be nice to have a parameter to set the timeout for this if possible. 

Regards

Kev

**Comment by xbauquet** [comment]
Hi, 
Thank you for your issue. This sounds like a good idea. But I just read the code and it seems that you already can change the duration of the banner display. Here is the code: 
```
public var duration: TimeInterval = 5.0 {
        didSet {
            updateMarqueeLabelsDurations()
        }
    }
```
`duration` is public so you can set it.
I haven't tested this. Maybe you could try to use it and come back here tell me if it's working or not.
If it is working I think you can close this issue ;)

**Comment by uradox** [comment]
You are right, dont know how I missed that! 
Thanks heaps!
