### ISSUE TITLE
iPhoneX: StatusBarNotificationBanner covered by home bar when using .bottom in specific view.

### ISSUE THREAD

**Issue by RobbieZhuang** [Daltron/NotificationBanner#101]
`
let title = "Title"
let banner = StatusBarNotificationBanner(title: title, style: .warning)
banner.show(bannerPosition: .bottom, on: self)
`

**Comment by xbauquet** [comment]
Who is self ?
I think you can try that: 
`banner.show(bannerPosition: .bottom)`

**Comment by RobbieZhuang** [comment]
Hey xbauquet, thanks for the advice. [self] is the current view controller. I was trying to localize the notifications within individual view controllers, but I think I’ll just stick with what you said and reduce the length of each notification.

**Comment by xbauquet** [comment]
I'm glade I could help. 
Please close the issue if you are finished with this question.
