### ISSUE TITLE
StatusNotificationBanner is behind the status bar

### ISSUE THREAD

**Issue by jeop10** [Daltron/NotificationBanner#103]
Hello I'm trying to display a StatusNotificationBanner when a match in my application is cancelled, but I think I am making something wrong because this is what happens after a few seconds of the notification being displayed

![behind](https://user-images.githubusercontent.com/5445566/37491153-267e1046-289d-11e8-9014-569a018f4d3a.png)

This is how I am making the call

```swift
MyService.instance.cancelRunningMatch { (success) in
            if success {
                let banner = StatusBarNotificationBanner(title: "Match successfully cancelled", style: .success)
                banner.show()
                self.navigationController?.popViewController(animated: true)
            } else {
               print("error when trying to cancel match")
            }
            self.cancelBtn.isEnabled = true
        }
```
Could you please help me? thanks in advance!
Edit: It happens on the simulator (iPhone 7) and on a iPhone 6, but cannot replicate on an iPhone 8

**Comment by Daltron** [comment]
Hi @jeop10! That is strange. Do you know if the banner code is being ran on the main thread? Trying wrapping it in a DispatchQueue.main.async{} block and see if that helps.

**Comment by jeop10** [comment]
Hello @Daltron Thank you for answering I just tested the code now look like this 
```swift
                MyService.instance.cancelRunningMatch { (success) in
            if success {
                
                DispatchQueue.main.async {
                    let banner = StatusBarNotificationBanner(title: "Match successfully cancelled", style: .success)
                    banner.show()
                }
                
                self.navigationController?.popViewController(animated: true)
            } else {
                ErrorReporting.showMessage(title: "Error", msg: "when trying to cancel match")
            }
            self.cancelBtn.isEnabled = true
        }
```

But the issue continue. I dont really know if the code is being ran on the main thread, sorry. I can tell you that this code is processed after I get a response from an Alamofire request to my endpoint. Hope that helps. 

Thank you again

**Comment by mattbarker016** [comment]
Having the same issue. I'm presenting on the navigation controller. It works nicely on the iPhone X, but not with other devices.

**Comment by mattbarker016** [comment]
I tried [an old hack](https://stackoverflow.com/questions/26781837/display-uiview-above-apple-status-bar-in-ios-8/45640794#45640794) I've used before, and it does work. I added the line 
```
UIApplication.shared.statusBarView?.addSubview(self)
```
in the `if` and `else` block starting at Line 303 in `BaseNotificationBanner.swift`.

**Before** 

![simulator screen shot - iphone 8 - 2018-03-16 at 23 39 09](https://user-images.githubusercontent.com/8039928/37551280-4c548b98-2973-11e8-8c26-e2ed4cf4b439.png)

**After**

![simulator screen shot - iphone 8 - 2018-03-16 at 23 38 33](https://user-images.githubusercontent.com/8039928/37551284-55d43830-2973-11e8-975e-1ccf349a7e96.png)

**Comment by jeop10** [comment]
Hello @mattbarker016 thanks for the tip, how did you achieve to edit the `BaseNotificationBanner.swift` file? I installed the library using cocoaPod and from what I can understand my extension to UIApplication is not being used within the library.

**Comment by mattbarker016** [comment]
https://github.com/mattbarker016/NotificationBanner

**Comment by jeop10** [comment]
@mattbarker016 Thanks for the info I really appreciate it!

**Comment by BrettRosen** [comment]
Same issue here

**Comment by pawansn** [comment]
Hey, anyone solved this issue?

**Comment by jeop10** [comment]
Sorry that I took so much to answer, I have not yet found the solution to this problem, sorry.

**Comment by pawansn** [comment]
**I solved this issue** 

https://stackoverflow.com/questions/50699531/how-to-show-view-in-statusbar-in-ios?noredirect=1#comment88408269_50699531

**Comment by mattbarker016** [comment]
@Daltron Did this get resolved in a new release?

**Comment by mattbarker016** [comment]
I resolved this issue in a [fork](https://github.com/mattbarker016/NotificationBanner). Would love to see this solution or a better one merged into master!

**Comment by PatrykKaczmarek** [comment]
Issue still occurs.
