### ISSUE TITLE
how to display text label in center of the banner?

### ISSUE THREAD

**Issue by arshadsk5** [Daltron/NotificationBanner#106]
I am new to notification banner, i want to display the titles in the center of the notification banner, how can i do that. I am waiting for the reply, please let me  know whether it is possible or not,Please help.

**Comment by uknowmeright** [comment]
try this:

```
let banner = NotificationBanner(title: "Your Title", style: .success)
banner.titleLabel?.textAlignment = .center
banner.show()
```
