### ISSUE TITLE
Request priority system

### ISSUE THREAD

**Issue by Alex293** [Daltron/NotificationBanner#11]
Hi ! Nice lib !
I'm thinking about extending your queue system with an arbitrary priority system (a bit like NSConstraint). You add the notification with a priority value and then the queue decide the display order instead of when it's added. We could set default like high number for error, small for info.

I don't know if I'm clear but this system would reduce dev think about should my banner go on top or on the bottom of the queue :)

**Comment by Daltron** [comment]
Hi @Alex293! 😄 

First off, I'm glad to hear you are enjoying the library! I've put quite a bit of thought into your request and I don't think NotificationBanner would benefit from this. I think displaying a banner on a queue is binary as in, I either want to show it immediately or I don't. I think adding a priority system complicates things just slightly from a usability point of view. If others or yourself have opinions on this, I'd love to hear them!

Thanks!
