### ISSUE TITLE
Crash on init StatusBarNotificationBanner

### ISSUE THREAD

**Issue by zhuravel-sergey** [Daltron/NotificationBanner#111]
On this line crash: `let bannerNoInternet = StatusBarNotificationBanner(title: ".no internet connection", style: .danger)`
<img width="1658" alt="screen" src="https://user-images.githubusercontent.com/7910769/40851512-4d5da6f2-65d0-11e8-8712-4e9116c86d9e.png">

**Comment by fazzerasty** [comment]
This will happen if you had a non-optional UIWindow property stored in you app delegate as this piece of code tries to force unwrap the property.

**Comment by Daltron** [comment]
@fazzerasty Can you think of a reason why a UIWindow property would be nil on an app delegate instance?
