### ISSUE TITLE
Banner Not Displaying

### ISSUE THREAD

**Issue by ttyguy1** [Daltron/NotificationBanner#114]
So I added the filling lines of code to the viewDidLoad() in my project

`let leftView = UIImageView(image: #imageLiteral(resourceName: "nextArrow"))
        let banner = NotificationBanner(title: "Hello World", subtitle: "HI", leftView: leftView, style: .success)
        banner.show()
        banner.haptic = .heavy
        banner.show()`

When I go run the app the status bar is hidden but then 5 seconds later it appears. So the banner is trying to load but all it does is just hides the status bar and you can't see the banner. Not sure if I'm missing something here. Any help would be great

**Comment by Mrweatherman208** [comment]
Try
DispatchQueue.main.async() {
let leftView = UIImageView(image: #imageLiteral(resourceName: "nextArrow"))
let banner = NotificationBanner(title: "Hello World", subtitle: "HI", leftView: leftView, style: .success)
banner.haptic = .heavy 
banner.show()
}

**Comment by ttyguy1** [comment]
BINGO! That was it. Thanks!
