### ISSUE TITLE
Banner width not changing when iPad orientation changed from portrait to landscape mode

### ISSUE THREAD

**Issue by UsmanIbnetariq** [Daltron/NotificationBanner#116]
Banner width not being set when I change orientation of iPad (on simulator, iOS version 10.3 and 11.4) from portrait to landscape and vice versa, I this a problem or expected behaviour?

**Comment by christoff-1992** [comment]
@UsmanIbnetariq - take a look at what I posted on #110

**Comment by UsmanIbnetariq** [comment]
I'm using a singleton to check connectivity and show banner that I initialise in didFinishLaunchingWithOptions below is code of Connectivity Manager class, can you guide me where exactly to include/use this work around because I've been trying to fix this issue from past few but couldn't resolve it

`class ConnectivityManager: NSObject {
    
    static let shared = ConnectivityManager()
    var connectivityStatus : Bool?
    
    private override init() {
        super.init()
        ApiManager.checkConnection {(status) in
            if self.connectivityStatus != nil{
                if status{
                    let banner = StatusBarNotificationBanner(title: "Connected", style: .info)
                    banner.show()
                    self.connectivityStatus = status
                }else{
                    let banner = StatusBarNotificationBanner(title: "No Internet Connection", style: .danger)
                    banner.show()
                    self.connectivityStatus = status
                }
            }else{
                if status{
                    self.connectivityStatus = status
                }else{
                    self.connectivityStatus = status
                }
            }
        }
    }
}`

**Comment by christoff-1992** [comment]
@UsmanIbnetariq - Its a change to the framework, you will have to fork the repo and make the change in the source code for it to take affect.
