### ISSUE TITLE
banner.show(on: viewController) doesn't show the banner below the navbar

### ISSUE THREAD

**Issue by sheinix** [Daltron/NotificationBanner#117]
Hi, I'm trying to show the banner below the Navbar following the instructions but it's not working. It is showing it on top like normal one.

```
let banner = NotificationBanner(title: "TITLE", subtitle: "SUBTITLE. \n \n MORE TEXT", style: .info)
banner.show(on: self)
```
What am I missing?

**Comment by falipate** [comment]
Wondering if this is achievable?
