### ISSUE TITLE
Left view constraints not working properly

### ISSUE THREAD

**Issue by fschaus** [Daltron/NotificationBanner#119]
Hello,

First off, great library - super easy to use, powerful and quite flexible/ comprehensive! I having just a minor issue - when trying to implement a left Image View with a corner radius it doesn't work.

My approach is to set a corner radius to the layer of the UIView like you would normally do. After a bit of digging, the issue seems to be that the SnapKit constraints can't be simultaneously satisfied (debug console) and therefor get broken with a resulting height/ width of 0 being set to the LeftView... This means that the moment I activate clip to bounds, my image "disappears" (or rather is clipped to (0,0). 

Here is my code:

```

var leftView = UIView()
var imageView = CircleImage(image: #imageLiteral(resourceName: "profileDefault"))
leftView.addSubview(imageView)

let banner = NotificationBanner(title: channelTitle ?? "New message", subtitle: message, leftView: leftView, style: .info)
                        
leftView.autoSetDimensions(to: CGSize(width: (banner.bannerHeight - 45), height: (banner.bannerHeight - 45)))
imageView.autoPinEdgesToSuperviewEdges()
imageView.autoSetDimensions(to: CGSize(width: (banner.bannerHeight - 45), height: (banner.bannerHeight - 45)))

imageView.layer.cornerRadius = imageView.frame.height / 2
imageView.contentMode = .scaleAspectFill
leftView.layoutIfNeeded()
imageView.clipsToBounds = true

```

Any idea how to override the constraints set on the left UIView by SnapKit? I tried using PureLayout without success. I tried different approaches (like not using PureLayout, etc.) but with no success so far...

Thanks for any help!

**Comment by Daltron** [comment]
Hi @fschaus! 😄 Your getting the "can't be simultaneously satisfied message" because your trying to put two sets of different constraints on the same view. Before adding your custom constraints, I would try clearing the constraints that the left view already has by calling `leftView.snp.removeConstraints()` and see if that helps.

**Comment by fschaus** [comment]
Thanks for the (super quick) reply! Taking a bit more time to think this through, I made 2 adjustments to simplify my code:
- I'll stop using PureLayout as it's a bit stupid to risk creating conflicting between PureLayout and SnapKit (as you correctly pointed out) and to go through the effort of re-setting all constraints you set with SnapKit using PureLayout (waste of time) :)
- Second, I should stop using a UIView and then embedding a UIImage into it, as the leftView can directly be declared as a UIImage (saves 2-3 lines of code + lowers the # of constraints to handle)

That being said, going with this more vanilla approach I still get the "unable to satisfy constraint" when all is this:
```
var imageView = CircleImage(image: #imageLiteral(resourceName: "profileDefault"))

let banner = NotificationBanner(title: channelTitle ?? "New message", subtitle: message, leftView: imageView, style: .info)
            
imageView.layer.cornerRadius = imageView.frame.height / 2
imageView.contentMode = .scaleAspectFill
imageView.layoutIfNeeded()
imageView.clipsToBounds = true
```

As you can see I don't make any adjustments to the constraints but still get a unable to satisfy constraints message and the constraints engine reset the height and width of my imageView to 0 (which then stops me from setting my corner radius/ clip to bounds). 

Any idea what can cause these unable to satisfy constraints? Looking at the debug messages (see below), my interpretation is that the UIImageView sets its constraints in relation to the banner vier (the 'UIView' in the debug message) but the UIView is given an active height & width constraint of 0 at the moment when the constraint engine tries to set the UIImageView constraint.

Do you have any suggestions as to how I can either force my UIImageView to reset its constraints once the bannerView constraints has changed (i.e., once it appeared) or to cancel the UIView height constraints?

Thanks a ton! 
Francois   

Here are the debug messages:
```
    "<NSAutoresizingMaskLayoutConstraint:0x13a42d4f0 h=--& v=--& UIView:0x13a423280.height == 0   (active)>",
    "<SnapKit.LayoutConstraint:0x13a4279f0@NotificationBanner.swift#67 Tap__.CircleImage:0x13a424cf0.top == UIView:0x13a423280.top + 10.0>",
    "<SnapKit.LayoutConstraint:0x13a428570@NotificationBanner.swift#69 Tap__.CircleImage:0x13a424cf0.bottom == UIView:0x13a423280.bottom - 10.0>"
)

Will attempt to recover by breaking constraint 
<SnapKit.LayoutConstraint:0x13a428570@NotificationBanner.swift#69 Tap__.CircleImage:0x13a424cf0.bottom == UIView:0x13a423280.bottom - 10.0>
```

and: 
```
    "<NSAutoresizingMaskLayoutConstraint:0x14250aaa0 h=--& v=--& UIView:0x13a423280.width == 0   (active)>",
    "<SnapKit.LayoutConstraint:0x13a4288c0@NotificationBanner.swift#70 Tap__.CircleImage:0x13a424cf0.width == Tap__.CircleImage:0x13a424cf0.height>",
    "<SnapKit.LayoutConstraint:0x139f153f0@NotificationBanner.swift#97 MarqueeLabel.MarqueeLabel:0x13a428ce0.left == UIView:0x13a4272a0.left>",
    "<SnapKit.LayoutConstraint:0x139f06bb0@NotificationBanner.swift#98 MarqueeLabel.MarqueeLabel:0x13a428ce0.right == UIView:0x13a4272a0.right>",
    "<SnapKit.LayoutConstraint:0x13a4280c0@NotificationBanner.swift#68 Tap__.CircleImage:0x13a424cf0.left == UIView:0x13a423280.left + 10.0>",
    "<SnapKit.LayoutConstraint:0x139f220d0@NotificationBanner.swift#126 UIView:0x13a4272a0.left == Tap__.CircleImage:0x13a424cf0.right + 15.0>",
    "<SnapKit.LayoutConstraint:0x139f22350@NotificationBanner.swift#134 UIView:0x13a4272a0.right == UIView:0x13a423280.right - 15.0>"
)

Will attempt to recover by breaking constraint 
<SnapKit.LayoutConstraint:0x139f06bb0@NotificationBanner.swift#98 MarqueeLabel.MarqueeLabel:0x13a428ce0.right == UIView:0x13a4272a0.right>
```

**Comment by Daltron** [comment]
@fschaus Could you setup a demo project showcasing this issue and send it to my email listed on this repo? I should be able to help you better if I can see whats actually going on.
