### ISSUE TITLE
I tried to use it in OC, but I couldn't call its functions

### ISSUE THREAD

**Issue by miliPolo** [Daltron/NotificationBanner#12]
I tried to use it in OC, but I couldn't call its functions

**Comment by Daltron** [comment]
Hi @miliPolo! 😄 I have no idea what OC means. Could you please explain?

Thanks!

**Comment by miliPolo** [comment]
OC means Object-C

This is the code in MyProjectName-Swfit.h ,i can't find the functions  of StatusBarNotificationBanner

SWIFT_CLASS("_TtC8LeftMost27StatusBarNotificationBanner")
@interface StatusBarNotificationBanner : BaseNotificationBanner
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end 

I hope you can help me

**Comment by Daltron** [comment]
@miliPolo Please look over #3 as this question has been asked before.

Thanks!

**Comment by miliPolo** [comment]
Thank you for your answer

**Comment by Daltron** [comment]
@miliPolo Your welcome, enjoy! 😄
