### ISSUE TITLE
Bottom banner y start at safe area

### ISSUE THREAD

**Issue by lyc2345** [Daltron/NotificationBanner#120]
Hi, Thanks for this awesome banner.
I have an issue about adjust bottom banner y position in iPhoneX.

I found it shows no matter with viewController or not. The y position always at `safeAreaInsets.bottom` which will leave blank underneath banner.

```
 let banner = NotificationBanner(customView: collectedPostBanner)
    if #available(iOS 11.0, *) {
      bannerHeight = Utility.isiPhoneX() ? 48 + (UIApplication.shared.keyWindow?.safeAreaInsets.bottom ?? 0) : 48
    } else {
      // Fallback on earlier versions
      bannerHeight = 48
    }
    collectedPostBanner.bannerHeightConstraint.constant = bannerHeight
    banner.bannerHeight = bannerHeight
    banner.show(queuePosition: .front,
                bannerPosition: .bottom,
                on: viewController)

// or 
    banner.show(queuePosition: .front,
                bannerPosition: .bottom)
```

[Screenshot](https://www.dropbox.com/s/i67hf6ocx8mv9yw/IMG_0312.png?dl=0)

Is there any method or variable could adjust the position?
Or I use it in the wrong way?

Thanks for reply.

**Comment by Daltron** [comment]
Hi @lyc2345! 😄 I'm a little confused. Are you wanting the banner to be at the very bottom attached over the bottom safe area?

**Comment by lyc2345** [comment]
YES YES!
