### ISSUE TITLE
How to show only the last called banner and dismiss all other banners in the queue?

### ISSUE THREAD

**Issue by jobinsjohn** [Daltron/NotificationBanner#123]

**Comment by Daltron** [comment]
Hi @jobinsjohn! 😄 Can you provide a little bit more context on what you are trying to achieve so I can better understand?

**Comment by samzhiwei** [comment]
Same festure, just like a Serial queue.
 I feel hard to override NotificationBannerQueue. Because removeAll() method is public, var banners and so on. Can not override removeAll() out of module
Or trying make NotificationBannerQueue become a protocol ?
Or any idea?

**Comment by samzhiwei** [comment]
banner.dismiss() is guarded by isDisplaying property
while banner is animating, banner can not be dismiss

**Comment by kk143g** [comment]
1) Declare banner as global, like this
**var banner = NotificationBanner(title: "Success", subtitle: "Follow Successful", leftView: nil, style: .success)**

2) And then before showing any banner call this
**self.banner.dismiss()**
3) And then recreate banner or show previous one with
**Self.banner.show()**
