### ISSUE TITLE
Better dynamic title management

### ISSUE THREAD

**Issue by rubengarciam** [Daltron/NotificationBanner#125]
Firstly, great work so far! 😊

**Use case**

The app is iterating through a loop of items that will be added to an internal Database. I would like to display a banner that get's dynamically updated with, for example, the number of items saved i.e:

`23 out of 100 records saved`

**What I'm doing right now**

1. Setting the banner as always on 
`banner.autoDismiss = false`
2. Dynamically updating the title label with the new count
` banner.titleLabel?.text = "\(count) out of 100 records saved"`
3. Dismissing the banner when finished
`banner.dismiss()`

**Issues**

It seems the banner get's stuck if updating the label is too frequent or the number of updates is too big.

In my test: a loop of +1k items tends to _"kill"_ the banner in the 20-something update

**Thoughts**

Not sure why it is happening, maybe creating a new function that refreshes the View instead of forcing the label update could fix the issue?

`banner.update(title: "new title")`

Cheers!

**Comment by Daltron** [comment]
Hi @rubengarciam! 😄 This is a great use case! The banners use [MarqueeLabel](https://github.com/cbpowell/MarqueeLabel) to display the text so I assume its unable to handle all the quick changes back to back to back. However, I do know that if you were to provide a custom view with a single UILabel which basically mimics the banner you are wanting to show, that should would perfectly fine!

**Comment by rubengarciam** [comment]
Cool, good to know! Will give it a go :)

**Comment by Daltron** [comment]
@rubengarciam Any update on this? 😄
