### ISSUE TITLE
UIApplication.delegate must be used from main thread only

### ISSUE THREAD

**Issue by karthiksaral** [Daltron/NotificationBanner#126]
I used the pod 'NotificationBannerSwift' for show the banner, but sometimes in iOS 11+  it crashed or app gets freeze, I based the issue in both (iPad & iPhone).
![screen shot 2018-08-14 at 2 52 38 pm](https://user-images.githubusercontent.com/5500927/44083743-7b1bc466-9fd2-11e8-8636-ccf1975d14b7.png)

**Comment by magiusdarrigo** [comment]
Has anyone found a solution to this issue? I am getting 5 lines of code in the swift locked files that say the same error. I am working with Swift 4.
