### ISSUE TITLE
swift 4.2

### ISSUE THREAD

**Issue by alfonso-matos-financefox-ch** [Daltron/NotificationBanner#128]
Hi,

Are you planning to have swift 4.2 compatibility?

Regards

Alfonso

**Comment by Daltron** [comment]
Hi @alfonso-matos-financefox-ch! I absolutely am. Feel free to make a PR if you have the time to do so!

**Comment by okdala2** [comment]
Fixing the issues in my personal project now. Seems like most of the changes are to conform to enums.

**Comment by Daltron** [comment]
CocoaPods release 1.7.0 now supports Swift 4.2! 🎉
