### ISSUE TITLE
Cannot compile with Xcode 9.4.1 and Swift 4 anymore

### ISSUE THREAD

**Issue by twofish187** [Daltron/NotificationBanner#132]
I want to do:
 carthage update --platform iOS

My Cartfile: github "Daltron/NotificationBanner" "master"

xcodebuild is: 9.4.1
carthage version: 0.30.1

I get the following error:

Building scheme "MarqueeLabel" in MarqueeLabel.xcworkspace
*** Building scheme "MarqueeLabelSwift" in MarqueeLabel.xcworkspace
*** Building scheme "SnapKit" in SnapKit.xcworkspace
*** Building scheme "NotificationBanner" in NotificationBanner.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/thaehnel/DEV/Vaccy/Vaccy/Carthage/Checkouts/NotificationBanner/NotificationBanner.xcodeproj -scheme NotificationBanner -configuration Release -derivedDataPath /Users/thaehnel/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/NotificationBanner/7624a21373897bf2fd2b8a3eed48de2e063c917b -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/nc/9dz9c4214jz35hm7nnkz2lrr0000gp/T/NotificationBanner SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/thaehnel/DEV/Vaccy/Vaccy/Carthage/Checkouts/NotificationBanner)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/nc/9dz9c4214jz35hm7nnkz2lrr0000gp/T/carthage-xcodebuild.1j9hKT.log
[carthage-xcodebuild.1j9hKT.log](https://github.com/Daltron/NotificationBanner/files/2386580/carthage-xcodebuild.1j9hKT.log)

How can I fix this or can you?

**Comment by Daltron** [comment]
Hi @twofish187!  I am completely unfamiliar with how Carthage works so I unfortunately can not help. @Dschee any chance you could help out here?

**Comment by sieren** [comment]
I had the exact same issue, @Daltron just merged the fix here: 
https://github.com/Daltron/NotificationBanner/pull/131 since Carthage uses the project file :)

**Comment by Daltron** [comment]
@sieren, thanks for the reply! You are correct that xCode 9.x does not support Swift 4.2.
