### ISSUE TITLE
iPhone XR & XS Max Simulator Position missed

### ISSUE THREAD

**Issue by baryon** [Daltron/NotificationBanner#135]
Compare these screenshot. build the latest version, and updated to snapkit 4.0.1, XCode 10.

the example is same. and the bottom position is not correct on  iPhone XR & XS Max

<img width="409" alt="iphone_8_-_12_0" src="https://user-images.githubusercontent.com/421757/45668265-12fe3a80-bb57-11e8-9b18-e15c4395cad9.png">
<img width="400" alt="iphone_x_-_12_0" src="https://user-images.githubusercontent.com/421757/45668337-50fb5e80-bb57-11e8-8cf4-4758abfd17f0.png">
<img width="401" alt="iphone_xs_-_12_0_ _app_store" src="https://user-images.githubusercontent.com/421757/45668371-725c4a80-bb57-11e8-9280-5d47ae43a0d4.png">
<img width="435" alt="iphone_xr_-_12_0" src="https://user-images.githubusercontent.com/421757/45668400-9324a000-bb57-11e8-8823-d18288a24eeb.png">
<img width="442" alt="iphone_xs_max_-_12_0_ _iphone_xs_-_12_0_ _app_store" src="https://user-images.githubusercontent.com/421757/45668451-bd765d80-bb57-11e8-95e5-e3c1b7ebc25a.png">

**Comment by Daltron** [comment]
Hi @baryon! 😄 As long as you pull down from the master branch, this issue should be addressed.
https://github.com/Daltron/NotificationBanner/pull/133
