### ISSUE TITLE
Stop building on latest

### ISSUE THREAD

**Issue by goeltarun** [Daltron/NotificationBanner#139]
It is giving me compilation error for MarqueeLabel 3.2.0, I have not ported my code to 4.2, even using older version of NotificationBanner is giving MarqueeLabel 3.2.0, which is giving me compilation error.

**Comment by Daltron** [comment]
Hi @goeltarun! 😄 Can you show me what your Podfile looks like please?

**Comment by goeltarun** [comment]
sure 
```
    pod 'Masonry', '~> 1.1'
    pod 'SnapKit', '~> 4.0'
    pod 'TPKeyboardAvoiding', '~> 1.3'
    pod 'MGSwipeTableCell', '~> 1.6'
    pod 'PXAlertView', '~> 0.1'
    pod 'YLProgressBar', '~> 3.10'
    pod 'NYTPhotoViewer', '~> 2.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'NotificationBannerSwift', '~> 1.6.3'
```

**Comment by goeltarun** [comment]
Also to note even if I give
```pod 'MarqueeLabel', '~> 3.1.6'```
it gives me error for duplicate property

**Comment by Daltron** [comment]
Instead of `pod 'NotificationBannerSwift', '~> 1.6.3'`, can you change it to `pod 'NotificationBannerSwift', '1.6.3'` and see if that addresses your problem?

**Comment by goeltarun** [comment]
unfortunately no :(, even if I give ```pod 'NotificationBannerSwift', '1.6.2'```, its till take ```Installing MarqueeLabel (3.2.0)```

And if is specifically gives ```pod 'MarqueeLabel', '3.1.6'``` in my podfile, it installs 3.1.6 version but gives error
![screen shot 2018-09-19 at 12 26 38 pm](https://user-images.githubusercontent.com/22160202/45767182-7e074a00-bc07-11e8-87ab-e9b49d6114ca.png)

**Comment by Daltron** [comment]
Can you show me what your Podfile.lock is please?

**Comment by goeltarun** [comment]
unfortunately no :(, even if I give pod ```'NotificationBannerSwift', '1.6.2'```, I get```Installing MarqueeLabel (3.2.0)``` and I get the error,
If I specify ```pod 'MarqueeLabel', '3.1.6'``` I get the following error.
![screen shot 2018-09-19 at 12 26 38 pm](https://user-images.githubusercontent.com/22160202/45767339-eb1adf80-bc07-11e8-86dc-a9a6319cc64c.png)

**Comment by goeltarun** [comment]
sure adding screen shot
<img width="1437" alt="screen shot 2018-09-19 at 12 35 10 pm" src="https://user-images.githubusercontent.com/22160202/45767587-91ff7b80-bc08-11e8-80b5-df5c12fc9dcc.png">

**Comment by goeltarun** [comment]
I think I may know the issue, here
https://github.com/Daltron/NotificationBanner/commit/b284f02d431804eb3cc1148f13cb4886c828be10#diff-d1586bc52e91ed192cc5baa589183bf5
it was ```s.dependency 'MarqueeLabel/Swift'``` so it always downloads the latest even if go back to some older vesions which is 3.2.0 now, which my project doesn't support, i guess if I want to use the library I  have to use port it to be able to use 3.2.0 of MarqueeLabel

**Comment by ZaVyLoN** [comment]
`'NotificationBannerSwift', '1.6.3'`
Don't work.

**Comment by ZaVyLoN** [comment]
![2018-09-20 2 02 32](https://user-images.githubusercontent.com/3078481/45787349-8a2dee80-bc7d-11e8-9bf8-7d8316daf2c4.png)

**Comment by ZaVyLoN** [comment]
Hi, @Daltron 
What about my error?

NotificationBannerSwift (by default 1.7.0)
MarqueeLabel  (by default 3.2.0)  See the errors above.

And now after install:
>  $ pod install
> Analyzing dependencies
> Downloading dependencies
> Using NotificationBanner (1.0.6)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

**Comment by Daltron** [comment]
@ZaVyLoN If your not building your project with Swift 4.2, then you will need to specify a version of NotificationBanner that supports the current swift version you are trying to target within your Podfile

**Comment by ZaVyLoN** [comment]
@Daltron, thx.

**Comment by Daltron** [comment]
I'm going to go ahead and close this issue as it is not a problem with NotificationBanner itself.

**Comment by goeltarun** [comment]
@Daltron ```pod 'MarqueeLabel', '3.1.6'``` should be great. Basically I don't need MarqueeLabel in my project, I was just trying to avoid the 3.2.0 for which I have to move to 4.2.0.

**Comment by goeltarun** [comment]
If you can make an intermediate release may be 1.6.4 with pointing to ```pod 'MarqueeLabel', '3.1.6' ``` that would work for us. Thanks all for the help.

**Comment by Daltron** [comment]
@goeltarun There is no need for a custom release. Here are the steps you need to follow:

1. Delete the Podfile.lock from your project
2. Add `pod 'MarqueeLabel', '3.1.6'` to your podfile

**Comment by goeltarun** [comment]
@Daltron thanks, will try. The issue though is the  ```Podfile.lock``` is generated for me after  I run pod install and that has the MarqueeLabel as 3.2.0 for NotificationBanner, thanks for help though, let me try something.

**Comment by Daltron** [comment]
@goeltarun I tried the steps above and it worked as expected for me.

**Comment by goeltarun** [comment]
sure, thanks will work with it.

**Comment by goeltarun** [comment]
@Daltron I got it working by

`pod 'NotificationBannerSwift', '1.6.3'`
`pod 'MarqueeLabel/Swift', '3.1.6'`
