### ISSUE TITLE
xcode10 and swift 4.2 support

### ISSUE THREAD

**Issue by Smiller193** [Daltron/NotificationBanner#141]
I know the app says xCode 4.2 is supported however when I try to build it I get these errors. Any idea what could be going wrong.
<img width="366" alt="screen shot 2018-09-20 at 5 03 23 pm" src="https://user-images.githubusercontent.com/16108750/45847013-7f17a480-bcf7-11e8-848a-77318aeddf4b.png">

**Comment by joaquin102** [comment]
Same here.

**Comment by weakfl** [comment]
The `SnapKit` dependency is not Swift 4.2 compatible yet.
Add a post install hook like this one to your Podfile until it gets updated:

```
swift4pods = ["SnapKit", "SomeOtherPod"]
post_install do |installer|
    # Fix Swift version setting
    installer.pods_project.targets.each do |target|
        if swift4pods.include? target.name
            print "Setting #{target.name}'s SWIFT_VERSION to 4.0\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Comment by IvanovDeveloper** [comment]
For me too

**Comment by weakfl** [comment]
Did you call `pod install` after adding the post install hook?

Also are you refering to the sample app or the `NotificationBannerSwift` pod? I'm just consuming the pod itself and it's working fine if the SWIFT_VERSION of the `SnapKit` dependency is set to Swift 4.0

**Comment by goeltarun** [comment]
I was getting the same error, got it working by

```    pod 'NotificationBannerSwift', '1.6.3'
    pod 'MarqueeLabel/Swift', '3.1.6' ```

**Comment by Smiller193** [comment]
@goeltarun thanks that got it working for me as well

**Comment by joseantoniogarciay** [comment]
post_install do |installer|
    installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              if target.name != 'MarqueeLabel' && target.name != 'NotificationBannerSwift' 
                config.build_settings['SWIFT_VERSION'] = '4.1'
              end
            end
    end
end

try this in your podfile

**Comment by Daltron** [comment]
This should now be resolved 👍
