### ISSUE TITLE
StatusBarNotificationBanner will be appear to bottom of screen on iPhone Xs Max.

### ISSUE THREAD

**Issue by r-plus** [Daltron/NotificationBanner#144]
`StatusBarNotificationBanner` will be appear to bottom of screen on iPhone Xs Max.

## version

- NotificationBannerSwift 1.7.1 installed from Cocoapods.
- Xcode10
- iPhone XS Max simulator iOS 12.0

## code

```
        let banner = StatusBarNotificationBanner(title: "downloading \(radio.id!)")
        banner.show()
```

## SS

![simulator screen shot - iphone xs max - 2018-09-23 at 21 59 18](https://user-images.githubusercontent.com/425216/45928294-3886ac00-bf7c-11e8-9b8d-40eef6286914.png)

## on 1.7.0

When I downgrade to v1.7.0, banner will be correctly on the statusbar.
So #140 is not good change for iPhone XS Max at least.

**Comment by amkomatzftx** [comment]
I am having this issue as well

**Comment by joseantonioECI** [comment]
@amkomatzftx can you check your podfile.lock?

This project ( [https://we.tl/t-0kKMvxG6cQ](https://we.tl/t-0kKMvxG6cQ) ) has those and works well
  - MarqueeLabel/Swift (3.2.0)
  - NotificationBannerSwift (1.7.1):
    - MarqueeLabel/Swift (~> 3.2.0)
    - SnapKit (~> 4.0.1)
  - Reveal-iOS-SDK (1.6.2)
  - SnapKit (4.0.1)

**Comment by r-plus** [comment]
@amkomatzftx I no longer reproduce this issue after clean and rebuild.
So the cause may be a cache before update for Xcode 10.
Could you try clean(Cmd+K) your project?
