### ISSUE TITLE
Xcode 9.4.1 build issue

### ISSUE THREAD

**Issue by rajtharan-g** [Daltron/NotificationBanner#147]
![screen shot 2018-09-25 at 7 19 50 pm](https://user-images.githubusercontent.com/23209069/46018713-23cf2300-c0f8-11e8-9b6e-c1804c4f6711.png)
Getting the build error as above when building the project. The project builds in Swift 4.1. 

I have the following in my pod file 
pod 'NotificationBannerSwift', '1.6.3'
pod 'MarqueeLabel', '3.1.6'

**Comment by maxibravo** [comment]
I have the same issue.

**Comment by rajtharan-g** [comment]
This is solved by changing the pod from 'MarqueeLabel' to 'MarqueeLabel/Swift' when building in Xcode 9.4.1 with Swift 4.1.
