### ISSUE TITLE
Very small banner on iPhone X

### ISSUE THREAD

**Issue by stealdre** [Daltron/NotificationBanner#148]
Hi,

I would like to know how to make the banner bigger? If I modify the height values in the  BaseNotificationBanner.swift file, nothing changes...

Thanks in advance for your help.

**Comment by 29satnam** [comment]
> I would like to know how to make the banner bigger?

I've found a trick, don't know if that's exactly what you want. But it's fine for me.

`            let banner = StatusBarNotificationBanner(title: "Unable to make connection, please check address & port.", style: .success)
            banner.bannerHeight = banner.bannerHeight + 5
            banner.show()`
This resolves issue of small banner for devices with notch and also add an extra 5 height for rest of the devices. Not a robust solution, though it meets my requirement.
cheers!
