### ISSUE TITLE
Title doesn't wrap to two lines when subtitle doesn't exist

### ISSUE THREAD

**Issue by btelintelo** [Daltron/NotificationBanner#153]
I am sending a title message to be displayed, no subtitle.  There is plenty of vertical space to have it go on two lines, but instead it marquees.  I see the code in NotificationBanner to set the title to two lines when no subtitle exists, but it isn't working.

**Comment by Daltron** [comment]
@btelintelo Unfortunately, this isn't how the base notification banner class is setup. If you want multiple lines for the title label, you'll need to use the custom view property!
