### ISSUE TITLE
Notification cannot be dismissed

### ISSUE THREAD

**Issue by btelintelo** [Daltron/NotificationBanner#154]
1. Create a notification that doesn't auto dismiss
2. Create a second notification that does dismiss
3. First notification can never be dismissed

The first notification gets suspended but never resumed
I should be able to dismiss a notification at any time, regardless if it is on top or not

**Comment by Daltron** [comment]
@btelintelo feel free to open up a pull request!

**Comment by btelintelo** [comment]
already working on it1
