### ISSUE TITLE
Status bar notification banner title not shown in iPhone Xs Max & Xr

### ISSUE THREAD

**Issue by vinayakpal** [Daltron/NotificationBanner#157]
I observe some changes in newly launched iPhone that it has not shown title text in iPhone Xs Max &   iPhone Xr. Similarly if notification banner title shown in the middle of the notch in iPhone Xs Max & Xr

**Comment by marekpivovarnik** [comment]
Same here...

**Comment by Daltron** [comment]
Hey guys! 😄 Feel free to open up a pull request as I do not have time to investigate every issue! Thanks!

**Comment by marekpivovarnik** [comment]
Migrating to Swift 4.2 and updating NotificationBanner pod to latest version seems to fix the problem for me ;) Sorry for false alarm...
