### ISSUE TITLE
onTap closure is not called on banner with customer view

### ISSUE THREAD

**Issue by MenuHunt** [Daltron/NotificationBanner#166]
Thanks for your great work!

I have the following code in my app to display a customer view, but onTap closure is not called when I tap the banner. In this example, it should but does not print "tapped". 

        let notificationVC = NotificationViewController(nibName: "Notification", bundle: nil)
        let banner = NotificationBanner(customView: notificationVC.view)
        banner.autoDismiss = false
        banner.onTap = {
            print("tapped")
        }
        banner.show()

**Comment by Daltron** [comment]
Hi @MenuHunt! :smile can you try keeping a strong reference to the banner object and see if that changes anything? If it doesn't, I'd be more than happy to investigate if you could send me an example project which replicates the issue.

**Comment by MenuHunt** [comment]
Thanks for your response. I figured out why it was not working. The reason was I had a big button covering the whole banner. That banner, I guess, was the first responder to the tap. After removing that unnecessary button, everything works now. Again thanks to your great work. It was my own mistake.
