### ISSUE TITLE
NotificationBanner Pod not updated for Swift 4.2

### ISSUE THREAD

**Issue by YMonnier** [Daltron/NotificationBanner#167]
Hi,

I have installed `NotificationBanner` through _Cocoapods_ and when I build my project, I have the following errors:

<img width="387" alt="screen shot 2018-11-09 at 9 47 49 am" src="https://user-images.githubusercontent.com/9322425/48252366-e226dd00-e404-11e8-9a11-3578fbc5d954.png">

### Pod install

```
pod install
Analyzing dependencies
Fetching podspec for `Sensa-Model` from `../../Sensa-Model`
Fetching podspec for `Sensa-Network` from `../`
Fetching podspec for `Sensa-Stylesheet` from `../../Sensa-Stylesheet`
Downloading dependencies
Using Alamofire (4.7.3)
Using AsyncSwift (2.0.4)
Using Freddy (3.0.3)
Using MarqueeLabel (3.2.0)
Using Moya (10.0.2)
Using Nimble (7.3.1)
Using NotificationBannerSwift (1.8.0)
Using ObjcExceptionBridging (1.0.1)
Using Quick (1.3.2)
Using ReachabilitySwift (4.3.0)
Using Realm (3.11.1)
Using RealmSwift (3.11.1)
Using Result (3.2.4)
Using Sensa-Model (1.0.46)
Installing Sensa-Network 1.0.18
Using Sensa-Stylesheet (1.0.6)
Using SnapKit (4.0.1)
Using SwiftMsgPack (1.0.0)
Using XCGLogger (6.1.0)
Generating Pods project
libs NotificationBannerSwift to Swift 3.2
libs NotificationBannerSwift to Swift 3.2
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 19 total pods installed.
```

### Stack

```
   CocoaPods : 1.5.3
   Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
   RubyGems : 2.7.4
   Host : Mac OS X 10.13.6 (17G65)
   Xcode : 10.1 (10B61)
   Git : git version 2.17.2 (Apple Git-113)
   Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
```

**Comment by stealdre** [comment]
@Daltron Same for me these devs are lost hahah

**Comment by janisgs** [comment]
Same...

**Comment by lozflan** [comment]
Same with me. I updated NotificationBanner from v1.6.3 to v1.8.0 today. Was working fine before except that banner was showing incorrectly on iPhone XS Max (not allowing properly for the notch & hence the reason for attempting the update). Now not working at all because of errors listed above. Is there a solution?

**Comment by krachtstefan** [comment]
Could this issue be related to https://github.com/Daltron/NotificationBanner/issues/168?

**Comment by aceisScope** [comment]
We solved this issue by manually setting the swift build version build settings of the NotificationBanner pod target to swift 4.2.

**Comment by jp-dubey07** [comment]
<img width="1010" alt="Screenshot 2019-11-16 at 21 59 39" src="https://user-images.githubusercontent.com/5441735/68996277-c7abfd00-08bd-11ea-9d33-f8efa8ea140d.png">
