### ISSUE TITLE
Update SnapKit version to 4.2.0

### ISSUE THREAD

**Issue by Arcovv** [Daltron/NotificationBanner#168]
SnapKit pod version was updated to 4.2.0, but in .podspec required to `~> 4.0.1`. So SnapKit could not  to use Swift 4.2 in my project.

**Comment by DanielBalsalobre** [comment]
Same problem here

**Comment by DanielBalsalobre** [comment]
> I made a quick monkey patch to make NotificationBanner work again until this is fixed.
> 
> `pod 'NotificationBannerSwift', :git => 'https://github.com/krachtstefan/NotificationBanner'`

Thanks, very useful

**Comment by deafjam** [comment]
> I made a quick monkey patch to make NotificationBanner work again until this is fixed.
> 
> `pod 'NotificationBannerSwift', :git => 'https://github.com/krachtstefan/NotificationBanner'`

Not work for me. Same 7 issues.

**Comment by Arcovv** [comment]
I fixed it. Change to `s.dependency 'SnapKit', '~> 4.2'` in .podspec would fix it.
https://github.com/Arcovv/NotificationBanner

If you met this problem, change your pod file to `pod 'NotificationBannerSwift', :git => 'https://github.com/Arcovv/NotificationBanner.git', :branch => 'master'` and run `pod update NotificationBannerSwift` in your terminal.
