### ISSUE TITLE
Dependency "NotificationBanner" has no shared framework schemes

### ISSUE THREAD

**Issue by miws** [Daltron/NotificationBanner#17]
$ carthage update
*** Fetching NotificationBanner
*** Checking out NotificationBanner at "1.2.0"
*** xcodebuild output can be found in /var/folders/3d/0_7l4jkd7pz0xpzzv56rddnh0000gn/T/carthage-xcodebuild.gg0Xl3.log
*** Skipped building NotificationBanner due to the error:
Dependency "NotificationBanner" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Daltron/NotificationBanner/issues/new

**Comment by Daltron** [comment]
@Dschee Any idea what's going on here? When I have time, I will beef up on my Carthage knowledge, but as of right now, if you could provide assistance, that would be greatly appreciated!

**Comment by Dschee** [comment]
@Daltron Thanks for asking, sure, no problem.

Sorry for not being clear about this from the beginning, but the "usual" way of including a framework is whithout specifying any specific branch or commit at all. This will default the installation to the latest released tag on GitHub, which is 1.2.0 apparently. But if I'm correct then this release was made before my PR got merged.

So the easiest solution to this problem ist to simply make a 1.2.1 or 1.3.0 release which adds Carthage support for the default installation method. I forgot to explicitly mention this, sorry for that. The alternative is for the Carthage user to soecify the branch name right after the framework entry in the Cartfile until a new release is made, like so:

github "Daltron/NotificationBanner" "master"

I hope this helps!

**Comment by Daltron** [comment]
@Dschee Thanks for the insight! 😄 @miws, for now, can you do what @Dschee said and point directly to the master branch until I release v1.3.0? I should be able to get around to it within the next couple weeks.

**Comment by Dschee** [comment]
Actually I think we can close this as #5 is merged and fixes this.

**Comment by miws** [comment]
@Dschee @Daltron thx.
I also did that.
