### ISSUE TITLE
Change banner default show time?

### ISSUE THREAD

**Issue by rhenz** [Daltron/NotificationBanner#18]
How to modify the banner's default show time or show it indefinitely and then hide it manually?

**Comment by Daltron** [comment]
Hey @rhenz! 😄 You will want to modify the banner's `duration` property. If you want to show it indefinitely, the simply pass in a large value to the `duration property`. I will open up an issue to add a feature request to make it easier to show an indefinite banner.

Thanks!

**Comment by rhenz** [comment]
Thanks @Daltron ! Cheers!
