### ISSUE TITLE
Legacy Swift Version when using ios pod

### ISSUE THREAD

**Issue by tdhman** [Daltron/NotificationBanner#183]
Hello,

I'm trying to use the library inside a Nativescript Plugin for my hybrid application, however, I got this error due to unspecified swift version. I also try to set the swift version for pod target in Podfile but did not work. Any idea to bypass this issue ?

> `NotificationBannerSwift` does not specify a Swift version and none of the targets (`demo`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Thanks for any help.

**Comment by gmarzloff** [comment]
I was having trouble building it for a swift3 project and successfully built the app by setting the Swift Language Version to 4.2 in Xcode: 

Pods -> Targets NotificationBannerSwift -> Build Settings tab -> Swift Language Version dropdown. 

Looks like it's a [common problem](https://github.com/Daltron/NotificationBanner/issues/167#issuecomment-450554021)

**Comment by tdhman** [comment]
Thanks @gmarzloff for your comment. That will also fix my problem if I use Xcode to build my app but as I use NativeScript build tools in command line to build my app, I cannot set the Swift version as you suggested because that error already occurs when NativeScript build tools try to build the Xcode project.
Since this is a common problem, should the library itself set the swift version to resolve that?

**Comment by gmarzloff** [comment]
@tdhman i added a[ pull request](https://github.com/Daltron/NotificationBanner/pull/184) to add `swift_version` to the podspec. you could try adding that to your podspec to see if it builds with NativeScript.  I haven't worked with NativeScript before, so I'm not sure if that will work though.
