### ISSUE TITLE
Cannot set dismiss time for NotificationBanner

### ISSUE THREAD

**Issue by superman566** [Daltron/NotificationBanner#185]
By default, it is 5s. But I feel it is longer, I need to set it shorter.

**Comment by usmanhaider4545** [comment]
banner.duration = 3

**Comment by superman566** [comment]
is it still working for v1.3? Because in my side, I am using swift 3.x.

**Comment by gmarzloff** [comment]
I haven't tested swift 3 (I use swift 4.2 and v2.01), but have you tried more extreme values for duration? The unit seems much longer than one second, so I set mine to 0.5 which feels right. 

`banner.duration = 0.5`
