### ISSUE TITLE
Banner if banner is active and when segueing to a new ViewController can not dismiss existing banner.

### ISSUE THREAD

**Issue by johnlietzke** [Daltron/NotificationBanner#189]
The banner begins a second time when active and switching to a new ViewController and can not be dismissed unless tapped.  The entire 5 seconds must be waited.

**Comment by andremietti** [comment]
the same here

**Comment by jagsrajput21** [comment]
@johnlietzke Did you find any solutions? I am having the same problem.

**Comment by DennisChatzim** [comment]
I have the same problem with the newer version Swift 5:
 If we have a StatusBarNotificationBanner which is set to .autoDismiss = false and it is visible, then if we try to dismiss it and immediately try to show another banner of any style then the first banner is never dismissed ! 
The only solution I found is to wait for the first banner until it is finished the dismissing (.dismissDuration) and then present the new banner.
Something like this:
let duration = 1.2 * (notInternetBanner?.dismissDuration ?? 0.5)
        DispatchQueue.main.asyncAfter(deadline: .now() + duration) {
            StatusBarNotificationBanner.showStatusBarBanner(message:"Connection restored", style: .success)
        }

**Comment by DennisChatzim** [comment]
Before every new .show() we can remove the banner by forcing removeFromSuperview like this:

static func removeAnyExistingBanner() {
        guard let window = AppDelegate.shared.window  else { return }
        
        let banners = window.subviews.filter { NSStringFromClass($0.classForCoder).contains("NotificationBannerSwift") }
        for b in banners {
            b.removeFromSuperview()
        }
    
        StatusBarNotificationBanner.notInternetBanner = nil
        StatusBarNotificationBanner.internetRestoredBanner = nil
        StatusBarNotificationBanner.marketStateBanner = nil
    }

**Comment by Clint1994** [comment]
@DennisChatzim  ^^ is this the way to dismiss any banners after segueing?

**Comment by DennisChatzim** [comment]
Before you present a new banner you can use the above method to make sure the new banner will be the only one visible.
After you present it the auto dismiss or tap feature will work great in order to hide again the new banner.
The problem was happening only if you try to present a new banner above an existing visible banner.
