### ISSUE TITLE
Status bar over banner

### ISSUE THREAD

**Issue by Bandyliuk** [Daltron/NotificationBanner#197]
Hello. Thanks for the library. I wrote code, that should solve next problem: when user complete some action, i need to show banner. If user fast done some actions(new banner call every 0.1-0.2 sec) and previous notifications still displayed, new notification showed over previous.

All work fine if user call code that written bellow slowly(every 2 seconds). But if user start call code fast(every 0.1-0.2 sec), status bar start displayed over banner and before dissmiss banner action. How to fix it? Or is it the same problem like on questions #103 and #149?

```
let banner = NotificationBanner(title: "Title", subtitle: "Subtitle", leftView: nil, style: .info)
banner.show(queuePosition: .front, bannerPosition: .top, queue: .init(), on: .none)
banner.duration = 2
```

PS: 

<img width="341" alt="Issue" src="https://user-images.githubusercontent.com/41991957/55635644-e1cf1a00-57c9-11e9-96a1-a30030857c73.png">

**Comment by Daltron** [comment]
Hi @Bandyliuk! 😄 Feel free to open up a PR for it if you think you have a fix!

**Comment by mattbarker016** [comment]
@Bandyliuk Thanks for making this issue. I just tried updating our [fork](https://github.com/Daltron/NotificationBanner/issues/103#issuecomment-374448316) to v2.1 while keeping the hack to resolve this issue, and it actually doesn't work any more.

**Comment by dregatos** [comment]
Hi @mattbarker016,

I ran into the same problem. Just use the `windowLevel` to temporarily hide the status bar, like the framework is already doing...

See, https://stackoverflow.com/a/44066303
