### ISSUE TITLE
Swift 5 and Xcode 10.2

### ISSUE THREAD

**Issue by osamaazmat** [Daltron/NotificationBanner#199]
Can you please update this library for swift 5 and Xcode 10.2?

**Comment by jcbriones** [comment]
NotificationBanner now supports Swift 5 but you have to manually specify the correct git. Also @Daltron, the dependency packages need to be updated as well since they also release a support for swift 5.

**Comment by Daltron** [comment]
Sorry for the delay everyone. I will try to update to the latest version of xCode so we can get an official Swift 5 cocoapods release. @jcbriones are you aware of which dependencies need updated? A PR would be greatly appreciated if you have the time!

**Comment by Daltron** [comment]
Cocoapods release `2.1.0` now contains Swift 5 support! 🎉

**Comment by jcbriones** [comment]
Sorry i just saw your comment but i guess you already did it. Thanks
