### ISSUE TITLE
Issue cocoapods

### ISSUE THREAD

**Issue by phynet** [Daltron/NotificationBanner#20]
Hello, it seems there's an issue with cocoapods installation. Unable to find a specification for NotificationBannerSwift. Maybe there is a issue with the name....

![captura de pantalla 2017-06-07 a las 12 24 19](https://user-images.githubusercontent.com/724536/26874013-4237e9fa-4b7c-11e7-9e9d-c21766445713.png)

**Comment by Daltron** [comment]
Hi @phynet! 😄 This is a common issue experienced within CocoaPods if your repo is out of date. Simply running the command `pod repo update` and then `pod install` should be all you need to do to get you going. Please report back if this works!

Thanks!

**Comment by phynet** [comment]
Sorry didn't answer sooner, I wasn't able to keep up with the project that was using your pod.

Indeed was cocoapods's outdated repo. Thanks for the answer, now is working :)

**Comment by Daltron** [comment]
@phynet Thanks for reporting back! Glad to hear that was the issue. 😄
