### ISSUE TITLE
How to add buttons to the banner?

### ISSUE THREAD

**Issue by ins0u** [Daltron/NotificationBanner#200]
Hello,

I like your project, it is easy and fast to use ^^

I have a question: Is it possible to put buttons in the banner like this ?

![banner](https://i.ibb.co/sVZ2bxZ/bannerbutton.png)

If it's possible, how ? 

Thx for your help ^^

**Comment by Daltron** [comment]
Hi @ins0u! 😄 You will need to create a custom view with the buttons then when you initialize your banner, use the `NotificationBanner(customView: yourCustomView)` initializer.

**Comment by ins0u** [comment]
Yes that's what I understood by downloading the examples..

With NorthCarolinaBannerView, you create your custom view programmatically but how create view with storyboard/xib ?
If you have a quick example, I can easily adapt it :D

Sorry for my question, I am a beginner with swift/xcode and thank you for your help :)

**Comment by ins0u** [comment]
Ok.. New Problem..

I create my customView with success.

This is my code : 

![bannerCustomView](https://user-images.githubusercontent.com/12513250/56964165-e84b7a00-6b5a-11e9-9147-23e5c63d6d97.png)

To use it, this is my code : 

```
let maCustomView = BannerEtesVousEnSecuriteView()
let banner = NotificationBanner(customView: maCustomView)
banner.autoDismiss = false
banner.show()
```

But I have a little problem with the result : 

![screenBannerBug](https://user-images.githubusercontent.com/12513250/56964660-ef26bc80-6b5b-11e9-9a40-2661f303fd87.png)

Why my customView does not come down below the buttons like in my xib ? :/
Have you an idea ? :)

**Comment by Vitalik13** [comment]
Hey @ins0u, easy way change banner.bannerHeight = 100. Best way set constraint and calculate height like GrowingBannerView
