### ISSUE TITLE
v2.2.0 doesn't work with MarqueeLabel 4.0.0

### ISSUE THREAD

**Issue by benweitzman** [Daltron/NotificationBanner#206]
Appears that MarqueeLabel is only supporting Swift and has dropped the name `MarqueeLabelSwift`  in favor of `MarqueeLabel` for imports, leading to the following error:

```
error: no such module 'MarqueeLabelSwift'
    import MarqueeLabelSwift
```

**Comment by Daltron** [comment]
Please feel free to open up a PR!
