### ISSUE TITLE
Left view image very small

### ISSUE THREAD

**Issue by tumispro** [Daltron/NotificationBanner#209]
Is it possible to make the left view a bit bigger? I added an imageview with an image as per the example, but it is a bit small.

![Simulator Screen Shot - iPhone Xʀ - 2019-06-27 at 21 37 06](https://user-images.githubusercontent.com/1461426/60295664-8de55480-9924-11e9-8d46-87b620a649d5.png)

```
let leftView = UIImageView(image: img!)
banner = GrowingNotificationBanner(title: "title", subtitle: "subtitle", leftView: leftView, style: .success)
banner?.show(bannerPosition: .bottom)
```

Lovely package btw! ❤️

**Comment by Daltron** [comment]
Hi @tumispro! I just pushed out a 2.3.0 to Cocoapods where you can set the `sideViewSize` when initializing a banner object like so:

```swift
let banner = GrowingNotificationBanner(title: "", subtitle: "", leftView: leftView, style: .success, sideViewSize: 48)
```

Does this work for you?

**Comment by tumispro** [comment]
Whew that was fast, and it works like a charm! Thank you so much for offering such excellent support!

**Comment by Daltron** [comment]
Glad to hear it works for you! Thanks for the kind words!

**Comment by ttansky** [comment]
Hi! But what if i use FloatingNotificationBanner? I can't add sideViewSize
