### ISSUE TITLE
Passing an object as a parameter on banner.onTap 

### ISSUE THREAD

**Issue by matin-kaj** [Daltron/NotificationBanner#21]
Is it possible to pass an optional parameter type of `Any` on `banner.onTap` for Banners with a Custom View ?

**Comment by Daltron** [comment]
Hi @matin-kaj! 😄 What exactly are you trying to accomplish? Could you provide me an example please so I can better understand? But to answer your question, no that is not possible.

**Comment by matin-kaj** [comment]
@Daltron Thanks for the replay. what I am trying to do is once I tap on custom banner view I would like to have an access to notificationId  as an object inside banner.onTap scope.
For instance , creating an instance like this with parameter 
` let banner = NotificationBanner(customView: customNotificationBannerView , withObject: someObject )  ` then once a user taps on banner inside callback function I have access to the object.
Thanks again

**Comment by Daltron** [comment]
@matin-kaj You can access `someObject` like this:

```swift

let banner = NotificationBanner(customView: customNotificationBannerView)
banner.onTap = {
   someObject.doSomething()
} 
```

There is no need to pass in a variable directly into the initializer.
Let me know if this helps!
