### ISSUE TITLE
Support translucency?

### ISSUE THREAD

**Issue by danqing** [Daltron/NotificationBanner#210]
Thanks for this great library! It has worked very well for me :)

I'm wondering if there's plan to support translucent banners. I think having such an option can make the banner look very native and polished in certain scenarios.

**Comment by Daltron** [comment]
Hi @danqing! 😄 Do you have a screenshot you could share? Also, feel free to open a PR if you have time and would like to take a stab at this!

**Comment by Daltron** [comment]
This can now be found in the `2.5.0` CocoaPods release by adjusting the `transparency` property on any type of notification banner! 

![Transparent Notification Banner](https://user-images.githubusercontent.com/9689335/61382858-28292000-a873-11e9-8a23-36ddbe41924c.png)

**Comment by danqing** [comment]
Hi @Daltron thanks for the reply!

I don't have time right now but maybe I can find some time to do it later if it hasn't been done by then. It's good that there's transparency support! However, I'm referring to translucency like the following (the matte glass effect signature to iOS) and not simply an alpha of < 1.

![](http://media.idownloadblog.com/wp-content/uploads/2014/12/Flesky-5.0-for-iOS-Translucent-theme-iPhone-screenshot.jpg)

**Comment by fukemy** [comment]
i want to add blur effect below but got dark background only, did u solved this?
