### ISSUE TITLE
Please fix issue - banner is not dismissing

### ISSUE THREAD

**Issue by Clint1994** [Daltron/NotificationBanner#212]
Hi there!

I have an issue when trying to dismiss a status bar banner if .autoDismiss = false

The first banner that appears does not dismiss when trying to .show another one. 

             ` if DataSnapshot.exists() {
                print(" Darn username already exists")
              
                noBanner.show()
                noBanner.autoDismiss = false
                
            } else {
                
                print("Yay I can use this username")
                noBanner.dimiss()
                successBanner.show()
                successBanner.autoDismiss = true
                
            }`

Thank you

**Comment by Daltron** [comment]
Hi @Clint1994! 😄 Can you create an example project demonstrating this issue please?

**Comment by Clint1994** [comment]
@Daltron  Yes of course! I'll get to it.

**Comment by Clint1994** [comment]
I actually figured the issue out, it was my code, learned more about how the queue works!
