### ISSUE TITLE
NotificationBanner rounded corners?

### ISSUE THREAD

**Issue by rigaldamez** [Daltron/NotificationBanner#213]
This is more of a question...

Is there an ability to show the banner with rounded corners?

thank you

**Comment by Daltron** [comment]
Hi @rigaldamez! 😄 This isn't currently possible. I will make this a feature request and will try to find some time to implement this. Stay tuned! 👍

**Comment by Daltron** [comment]
@rigaldamez is something like this what you are thinking?

![FloatingBanner](https://user-images.githubusercontent.com/9689335/61139631-4b2c8c00-a48f-11e9-921f-d2a71ea8a440.png)

**Comment by Daltron** [comment]
You should be able to accomplish this by using `FloatingNotificationBanner` in the `2.4.0` release! 🎉

**Comment by rigaldamez** [comment]
![image](https://user-images.githubusercontent.com/29295300/61166738-ed24a500-a571-11e9-9560-b54142e82580.png)
 Thats exactly what I meant :) - I have updated to the latest `2.4.0 `release but can't seen to see the option to create a `FloatingNotificationBanner`, am I missing something?

**Comment by Daltron** [comment]
This has been fixed in the CocoaPods `2.4.1` release!
