### ISSUE TITLE
GrowingNotificationBanner not working on Swift 5

### ISSUE THREAD

**Issue by jminutaglio** [Daltron/NotificationBanner#215]
GrowingNotificationBanner throws a SIGABRT.  using version v 2.4.0 when displaying on a UITableViewController - NotificationBanner works ok.

**Comment by Daltron** [comment]
Hi @jminutaglio! Could you please provide some sample code or even better yet, a sample project showcasing this behavior please?

**Comment by jminutaglio** [comment]
I was passing subtitle: something that wasn't a string so this is my error and it can be closed.  may be an opportunity for better error handling but I have it working now.  ty for the quick reply!!
