### ISSUE TITLE
new transparency feature causes black background on banners with custom view

### ISSUE THREAD

**Issue by rurza** [Daltron/NotificationBanner#219]
`init(customView: UIView)` calls `init(style: BannerStyle, colors: BannerColorsProtocol? = nil)`  where `colors` parameter is nil. `BannerColors().color(for: style)` returns `.clearColor` (which is black with 0 opacity). Setter of backgroundColor (`let color = newValue?.withAlphaComponent(transparency)`) changes it to black color...

**Comment by Daltron** [comment]
Thanks for bringing this to my attention. This has been fixed in the CocoaPods `2.5.1` release!

**Comment by shles** [comment]
I assume this still in place

**Comment by vg-identance** [comment]
The issue still exists in `3.1.0`
