### ISSUE TITLE
Option to format title and subtitle (style, color)

### ISSUE THREAD

**Issue by matin-kaj** [Daltron/NotificationBanner#22]
I just realized if I use white custom background color or `.none` the title and subtitle will become invisible.

**Comment by Daltron** [comment]
@matin-kaj  You have completely full control of how your `titleLabel` and `subtitleLabel` look. You can manually change the `titleLabel` and `subtitleLabel` text colors and many other properties by:

```swift
banner.titleLabel?.textColor = newTextColor
banner.subtitleLabel?.textColor = newTextColor
```
