### ISSUE TITLE
Animations?

### ISSUE THREAD

**Issue by JamesCastrejon** [Daltron/NotificationBanner#221]
This is a request for a new feature. I'm planning on using this since it's really neat and looks great, but I realized the animations are all the same.

What I mean is that they all seem to kinda just drop down from the top. This by no means is bad in any way, I was just wondering how cool it would be if there were more animations.

For example: It can appear over the span of 1 sec (0 to 100% opacity) or maybe instead of dropping down, it sorta slides in from the left or right. Maybe even a reverse page turn could be cool.

**Comment by ptseng** [comment]
I think it would also be a nice feature to be able to display the banner without the animation, or to be able to replace the frontmost banner being displayed without animations.
