### ISSUE TITLE
Bottom banner broken after rotation

### ISSUE THREAD

**Issue by maxilapo** [Daltron/NotificationBanner#222]
Hello, 

So my problem is when I rotate the iPad while the notification is showing.

**The code I use to show the banner**: 
`let banner = NotificationBanner(title: "lolol", subtitle: "subtitle", style: .success)
        banner.show(bannerPosition: .bottom)`

If I rotate the iPad while the notification is visible, i got this:
![Screenshot](https://user-images.githubusercontent.com/3606588/61817424-867a7380-ae1c-11e9-8754-ddbb395599c6.PNG)

Thanks :)

**Comment by tonythebully** [comment]
Hopefully this helps others, but I was able to fix it on a fork by changing the rotation notification that `BaseNotificationBanner.swift` was observing from:

`UIDevice.orientationDidChangeNotification`
to
`UIApplication.didChangeStatusBarOrientationNotification`

**Comment by garnele007** [comment]
> Hopefully this helps others, but I was able to fix it on a fork by changing the rotation notification that `BaseNotificationBanner.swift` was observing from:
> 
> `UIDevice.orientationDidChangeNotification`
> to
> `UIApplication.didChangeStatusBarOrientationNotification`

This should get fixed in the main branch.
