### ISSUE TITLE
___________ ... must be used from main thread only crashes in Swift 4.

### ISSUE THREAD

**Issue by magiusdarrigo** [Daltron/NotificationBanner#223]
Using the simple self.eventBanner.show() command does not show the banner and creates 5 errors about needing to be in the main thread.

![Screen Shot 2019-07-25 at 2 23 54 AM](https://user-images.githubusercontent.com/43056803/61854235-46021080-ae83-11e9-9bb3-14f8c6521aea.png)

What could I do to fix this? Thanks.

**Comment by Daltron** [comment]
You need to do exactly what it is telling you to do, to make sure you are calling `self.eventBanner.show()` on the main thread! 😃
