### ISSUE TITLE
iOS 13 private let appWindow: UIWindow = UIApplication.shared.delegate!.window!! crash

### ISSUE THREAD

**Issue by yushuyi** [Daltron/NotificationBanner#225]
iOS 13 use UIWindowScene .  private let appWindow: UIWindow = UIApplication.shared.delegate!.window!! crash

**Comment by ashleyevans** [comment]
this issue still exists on iOS 13, any plans to push a fix?

**Comment by Daltron** [comment]
Hi @ashleyevans! 😄 Please feel free to open a PR for this if you have one.

**Comment by ashleyevans** [comment]
Hi @Daltron i've submitted a PR :)

**Comment by Milap-Kundalia** [comment]
I am facing the same error it's still not working
