### ISSUE TITLE
Is there any way to update message of existing notification?

### ISSUE THREAD

**Issue by Akki9326** [Daltron/NotificationBanner#227]
I have a scenario to handle, in that I need to show a notification on one event but if event 2 will occur then I have to update the message of the same notification.

is there any way that I can do it?

and Thanks for a great library. 🤘🏽 😊

**Comment by Daltron** [comment]
Hi @Akki9326! 😄 What you are looking for is this `banner.titleLabel.text = yourText`. The same can also be done with the subtitle label!

**Comment by Akki9326** [comment]
Thank you @Daltron, I haven't seen your reply, but indirectly I have created a method that will update the subtitle for me.

And Again thanks for the great Library.
