### ISSUE TITLE
MarqueeLabel.type = left have to be changed in cocoa pods

### ISSUE THREAD

**Issue by younatics** [Daltron/NotificationBanner#23]
Please check cocoa pods gives me titleLabel!.type = .left

**Comment by Daltron** [comment]
It appears that when I uploaded a new version to CocoaPods, there is some kind of caching issue that is taking place. I have filed an [issue here](https://github.com/CocoaPods/CocoaPods/issues/6790) and will be watching it closely so this issue can be resolved as it is critical.

In the meantime as a temporary fix, change the way you add `NotificationBannerSwift` to your podfile like this:

```ruby
pod 'NotificationBannerSwift', :git => 'https://github.com/Daltron/NotificationBanner', :branch => 'master'
```

This will pull down the files that are supposed to be in v1.3.0 but somehow didn't make their way in.

**Comment by Daltron** [comment]
@younatics @nick-iCars I just pushed a new version 1.3.1 to CocoaPods that fixes this issue. You can change your Podfile back to `pod NotificationBannerSwift` and rerun `pod update NotificationBannerSwift` inside your project directory and you should be good to go.

Thanks for your patience! 😄

**Comment by nick-iCars** [comment]
Nice! I will check it out. Thanks 😄.
