### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by fchauvin** [Daltron/NotificationBanner#231]
Would love to see this now that Xcode 11 treats it as a first class citizen!

**Comment by Daltron** [comment]
Hi @fchauvin! 😄 This is definitely on my todo list, but all other dependencies like `MarqueeLabel` and `SnapKit` have to support SPM as well first.

**Comment by fchauvin** [comment]
Great! 

Looks like `SnapKit` has it supports on a master, and a PR is currently opened for `MarqeeLabel` for support. 👍

**Comment by lvnkmn** [comment]
`MarqueeLabel` now (or maybe a little while actually) has support for this in its [Xcode 11 branch](https://github.com/cbpowell/MarqueeLabel/tree/xcode11)

**Comment by danqing** [comment]
Can you cut a new version @Daltron so we can start using SPM? Thanks!

**Comment by Daltron** [comment]
Thanks for being patient everyone! `3.0.4` should not be accessible through SPM!
