### ISSUE TITLE
App doesn't recognize touches after banner is shown.

### ISSUE THREAD

**Issue by alperkayabasi** [Daltron/NotificationBanner#233]
Hello.
We have an application that shows NotificationBanner if the app receives a push notification when it is active.

This is the code, we show the alert in the simplest way, on the main window;

`let banner = NotificationBanner(title: title, subtitle: body, style: .none)
banner.show()`

After notification is shown on screen, the application window does not receive additional touches and gives this message in debug window:

`[Touch] unexpected nil window in __sendSystemGestureLatentClientUpdate, _windowServerHitTestWindow: <UIWindow: 0x105012da0; frame = (0 0; 414 736); autoresize = W+H; userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0x280c6df50>; layer = <UIWindowLayer: 0x28021cac0>>, touch:<UITouch: 0x10bc50660> phase: Stationary tap count: 1 force: 0.317 window: (null) view: (null) location in window: {0, 0} previous location in window: {0, 0} location in view: {0, 0} previous location in view: {0, 0}`

After that, user can not interact with anything on screen. Screen is still there though.

Is there anyone who encounters this?

**Comment by Daltron** [comment]
If you could provide a sample application, I would be happy to take a look! 😄

**Comment by Daltron** [comment]
Closing as I don't believe this is an issue with the library its self. Please feel free to re-open if you think otherwise.
