### ISSUE TITLE
GrowingNotificationBanner not available in objective-c

### ISSUE THREAD

**Issue by punto2018** [Daltron/NotificationBanner#236]
Hi,
the library is written in swift but works with minor issues  also with objective-c projects.
The class GrowingNotificationBanner can't be inited in objective-c so can't be used.
Can you please fix it?

Thanks

**Comment by Daltron** [comment]
Hi @punto2018! 😄 Unfortunately, I am not interested in keep NotificationBanner up to date to support  Objective-C. If you find a solution and want to open up a PR, I would be happy to take a look! 😄
