### ISSUE TITLE
Wrong changes in last release

### ISSUE THREAD

**Issue by mrsnow-git** [Daltron/NotificationBanner#237]
I looked at last release changes and see next thing:

in file NotificationBanner/Classes/FloatingNotificationBanner.swift : 134 

You added the guard for blurRadius. But this is mistake - shadow can exist even if blurradius == zero, but have offset. Why you added it?

**Comment by Daltron** [comment]
Hmmm this might have been a mistake on my end, but I'm not exactly sure. If you open up a PR, I would be happy to take a look! 😄

**Comment by mrsnow-git** [comment]
i'll add it after my current pr will be merged, to avoid possible merging problems for now... :)

**Comment by Daltron** [comment]
@mrsnow-git do you still plan on creating a PR for this?

**Comment by mrsnow-git** [comment]
Waiting for merge and new release ;)
