### ISSUE TITLE
Custom font won't apply

### ISSUE THREAD

**Issue by Abdulaziz-si** [Daltron/NotificationBanner#239]
Hello 
I'm trying to use a custom font for the title but it won't work , although I tried to change title color and it's fine however when it's come to font nothing is happening and no error showing up in the debug console
my code looks like this:

let rightView = UIImageView(image: #imageLiteral(resourceName: "change password icon").filled(withColor: .white))
            let banner = GrowingNotificationBanner(title: "Sorry please check your phone number", subtitle: nil, rightView: rightView, style: .danger)
            banner.applyStyling(titleFont: UIFont(name: "DroidKufi-Bold", size: 16), titleColor : UIColor.yellow)
            banner.show()

Do I miss something ??
please help
Thank you

**Comment by Daltron** [comment]
Hi @Abdulaziz-si! 😄 My guess is `UIFont(name: "DroidKufi-Bold", size: 16)` is returning nil. Can you check to see if this is the case. If it is, make sure to add it to your supported fonts in your plist file.

**Comment by Abdulaziz-si** [comment]
yes it was returning nil , something was missing in my plist
problem solved
thank you sooooo much
