### ISSUE TITLE
iOS 13: banner shown bellow Status Bar

### ISSUE THREAD

**Issue by oferRounds** [Daltron/NotificationBanner#240]
Hi,
Thanks for this awesome library!

Probably you encounter this bug already, but I couldn’t find an open issue regarding it

Starting from iOS 13, there’s a problem where the banner shows itself beneath the Status Bar

Is there a way to solve it?

Thanks a lot!

**Comment by igorkulman** [comment]
Same problem also on iOS 13.1, here is a screenshot running the sample app in 6S

![Simulator Screen Shot - iPhone 6s - 2019-09-25 at 11 28 28](https://user-images.githubusercontent.com/4746070/65588351-a72f8880-df87-11e9-924c-1080fa2ac8a2.png)

**Comment by StarWars** [comment]
It seems that on devices from the X family, top banners are not visible at all. They are hidden below the navigation bar or the status bar - I am not sure which one.

**Comment by Daltron** [comment]
Hey everyone! 😄 I am aware that this is kind of a critical issue for non-notch devices running iOS 13. Unfortunately, it doesn't look like the `UIWindow.windowLevel` property works anymore on iOS 13 with the introduction of scenes. I am more than happy to discuss possible solutions to help address this issue. Here is maybe what I am thinking: _For non-notch phones and status bar notifications, have the notification start below the status bar. This might look a bit weird but I'm not sure how else to make this directly work._

**Comment by igorkulman** [comment]
> Here is maybe what I am thinking: _For non-notch phones and status bar notifications, have the notification start below the status bar. This might look a bit weird but I'm not sure how else to make this directly work._

What about something like this? So starting in the status bar area but showing the text under it

![image](https://user-images.githubusercontent.com/4746070/65665057-ef5bb300-e03a-11e9-93f2-ad10a32e16a0.png)

I found it checking if other libraries have the same problem (and sure they have because of the reasons you mention)

**Comment by igorkulman** [comment]
Using some adjustments I got to this

![Simulator Screen Shot - iPhone 6s - 2019-09-26 at 11 47 02](https://user-images.githubusercontent.com/4746070/65678546-c98ed800-e053-11e9-83f0-4f312bac731c.png)

By updating `StatusBarNotificationBanner` and adding `heightAdjustment` property just for this case 

```swift
public override var bannerHeight: CGFloat {
        get {
            if let customBannerHeight = customBannerHeight {
                return customBannerHeight
            } else if shouldAdjustForNotchFeaturedIphone() {
                return 50.0
            } else {
                return 20.0 + heightAdjustment
            }
        } set {
            customBannerHeight = newValue
        }
    }

    private var heightAdjustment: CGFloat {
        guard #available(iOS 13.0, *), !NotificationBannerUtilities.isNotchFeaturedIPhone() else {
            return 0
        }

        return UIApplication.shared.statusBarFrame.height
    }

    override init(style: BannerStyle, colors: BannerColorsProtocol? = nil) {
        super.init(style: style, colors: colors)

        titleLabel = MarqueeLabel()
        (titleLabel as! MarqueeLabel).animationDelay = 2
        (titleLabel as! MarqueeLabel).type = .leftRight
        titleLabel!.font = UIFont.systemFont(ofSize: 12.5, weight: UIFont.Weight.bold)
        titleLabel!.textAlignment = .center
        titleLabel!.textColor = .white
        contentView.addSubview(titleLabel!)

        titleLabel!.snp.makeConstraints { (make) in
            make.top.equalToSuperview().offset(heightAdjustment)
            make.left.equalToSuperview().offset(5)
            make.right.equalToSuperview().offset(-5)
            make.bottom.equalToSuperview()
        }

        updateMarqueeLabelsDurations()
    }
```

**Comment by wiencheck** [comment]
If we can still access the status bar window by calling

‚UIApplication.shared.value(forKey: "statusBarWindow") as? UIWindow’ 

why don’t just hide the status bar or animate it so it slides up out of the screen and later returns?
Surely not the best solution but should do it for now

**Comment by oferRounds** [comment]
Looks good! I also think that’s a reasonable solution

**Comment by KoD4K** [comment]
Hi everyone!
But after update to 2.6.0, I don't see any notification on my simulators Xr and 8. Is it ok? May be someone else also get it or it's only my fault?
