### ISSUE TITLE
Status Bar not hidden and overlaps NotificationBanner on iOS 13

### ISSUE THREAD

**Issue by SergejLogis** [Daltron/NotificationBanner#247]
We use `NotificationBanner` to display toast notifications over the Status Bar. On iOS 13 Status Bar is not hidden when notification banner is presented, therefore its contents overlapped by Status Bar. We are using latest `NotificationBannerSwift 3.0.0`.

Overlapped on iOS 13.
![notificationbanner_statusbar](https://user-images.githubusercontent.com/32644729/66561597-72642980-eb62-11e9-9fae-a00b87415c51.jpeg)

Works fine on iOS 12.
![notificationbanner_ios12](https://user-images.githubusercontent.com/32644729/66562062-72185e00-eb63-11e9-8ede-56710f59d7c7.jpeg)

**Comment by Daltron** [comment]
Hi @SergejLogis! I just created a sample project using version 3.0.0 and everything is working as expected. Please make sure you are actually running version 3.0.0 and try again! 😄

**Comment by SergejLogis** [comment]
Thanks, Daltron!
I've tried to create a simple separate project with NotificationBannerSwift 3.0, but the issue is still there. Could you please share your code?
Thanks.

**Comment by Daltron** [comment]
@SergejLogis Can you upload your sample code here please so I can take a look?

**Comment by SergejLogis** [comment]
We use a custom view for notifications, and its class is quite large. But the actual notification is presented like that:
```
let banner = NotificationBanner(message: message, style: style, duration: duration, haptic: hapticType, autoDismiss: autohide, delegate: delegate)
banner.show(queue: bannerQueue, on: nil)
```

**Comment by Daltron** [comment]
@SergejLogis Without seeing your project, it's going to be nearly impossible for me to help determine why you are not seeing the 3.0.0 changes. The presentation of the banner is not the issue here. If you could create a separate demo project showcasing the issue, that would be extremely helpful.

**Comment by SergejLogis** [comment]
OK. I will try to do it :) Thanks!

**Comment by SergejLogis** [comment]
Since I'm using a custom view for notification, I have fixed the issue on my side. For some reason, `heightAdjustment` is ignored, so I just moved the message label down by the height of Status Bar in my custom view.
