### ISSUE TITLE
UIMenuController is not being displayed when NotificationBanner is present

### ISSUE THREAD

**Issue by wiencheck** [Daltron/NotificationBanner#248]
Before the new update for iOS 13 came out UIMenuController worked as desired, but now if NotificationBanner is visible I can't get it to display. When NotificationBanner disappears UIMenuController works as ususal.

**Comment by Daltron** [comment]
Hi @wiencheck! 😄 Please feel free to open up a pull request. I'm about 99% confident it has something to do with the adjustment of the status bar level.
