### ISSUE TITLE
How to 'opt out' of stacked banners?

### ISSUE THREAD

**Issue by wiencheck** [Daltron/NotificationBanner#253]
Even though I'm using the `.default` queue for displaying banners (which has the `maxBannersOnScreenSimultaneously` set to 1 by default) the banners are being displayed on a stack. I guess it's a bug, I'm using the `StatusBarNotificationBanner`, Tested on iOS 13.1

**Comment by Daltron** [comment]
Hi @wiencheck! 😄 Could you provide a GIF of what you are seeing as I am not currently see the issue in the example project.

**Comment by Daltron** [comment]
Actually, it looks like something unexpected is happening when your adding to the front of the queue. Is this the issue you are referring to?

![Simulator Screen Shot - iPhone 11 - 2019-10-22 at 09 20 23](https://user-images.githubusercontent.com/9689335/67295901-5ee38780-f4ad-11e9-8c10-a107732d8ff7.png)

**Comment by onevcat** [comment]
Same issue here. It happens when adding banner with `.front` queue position. 

The newly added `maxBannersOnScreenSimultaneously ` is never considered.

https://github.com/Daltron/NotificationBanner/blob/master/NotificationBanner/Classes/NotificationBannerQueue.swift#L54-L76
