### ISSUE TITLE
3.0.2 is not compileable

### ISSUE THREAD

**Issue by peacemoon** [Daltron/NotificationBanner#262]
Just run carthage update and it doesn't work. I'm using Xcode 11.1.

![Screenshot 2019-11-16 at 01 08 04](https://user-images.githubusercontent.com/478757/68983892-9542c700-080d-11ea-91f0-562a35ca1a5b.png)

**Comment by peacemoon** [comment]
It seems that this file `UIWindow+orientation.swift` is somehow missing.

**Comment by fredpi** [comment]
Same for me with Xcode 11.2

**Comment by fredpi** [comment]
Also doesn't work with `3.0.1` – `3.0.0` is the last working release

**Comment by peacemoon** [comment]
I open a PR to fix the issue https://github.com/Daltron/NotificationBanner/pull/263

**Comment by peacemoon** [comment]
@Daltron  thank you for merging my PR. Can you create a new tag so that `Carthage` works again. I'll close this issue afterward then.

**Comment by peacemoon** [comment]
@Daltron could you please create a new tag to include the fix in the PR.
The tag 3.0.2 is totally broken now.

**Comment by CognitiveWin** [comment]
This is still broken for me. Any updates?

Thanks for taking the time to fix this @peacemoon

**Comment by peacemoon** [comment]
@CognitiveWin you can point your carthage to "master" to fix the issue. But I still prefer to have a fixed version to avoid any unwanted changes with a moving master.

**Comment by Daltron** [comment]
Hi all, sorry for the delay! I just pushed a new tag `3.0.3`. Please let me know if this resolves the issue. Thank you all for being patient!
