### ISSUE TITLE
iOS 13 StatusBarNotificationBanner behind status bar

### ISSUE THREAD

**Issue by SRowley90** [Daltron/NotificationBanner#266]
It seems like iOS 13 when showing a StatusBarNotificationBanner it appears behind the status bar when i'd expect it to be on top. Working fine on iOS 12 in the Simulator.

**Comment by JonasSL** [comment]
I'm also experiencing this bug.

**Comment by jmanalang3** [comment]
the same problem with me, sometimes it disappears

**Comment by nbhhcty** [comment]
I'm also experiencing this bug

**Comment by Ze-ro-G** [comment]
Same problem here, did someone find a solution ?
