### ISSUE TITLE
'NotificationBanner' has no member 'haptic'

### ISSUE THREAD

**Issue by danlevy1** [Daltron/NotificationBanner#27]
I am working with Xcode 9 Beta 1 (maybe this is just a problem with code 9) and I cannot add the line `banner.haptic = .heavy` without getting the error "Value of type 'NotificationBanner' has no member 'haptic.'"

**Comment by Daltron** [comment]
Hi @danlevy1! 😄 Are you using CocoaPods or Carthage and what version are you using?

**Comment by danlevy1** [comment]
I am using CocoaPods with version 1.2.0.

**Comment by Daltron** [comment]
@danlevy1 Haptic feedback wasn't introduced until version 1.3.0. Try running a pod update to update to the latest version and let me know if that solves your problem.

**Comment by danlevy1** [comment]
You're right - thanks!
