### ISSUE TITLE
Problem with Swift Package Manager.

### ISSUE THREAD

**Issue by devLoop1-zz** [Daltron/NotificationBanner#278]
Hello, I have problems when adding to my project with Swift Package manager, it gives me the following error.

I hope you can help me.

![Captura de Pantalla 2020-01-05 a la(s) 17 55 19](https://user-images.githubusercontent.com/48538624/71785976-e177df80-2fe4-11ea-9ec4-dfbb84f1aad7.png)
![Captura de Pantalla 2020-01-05 a la(s) 17 54 50](https://user-images.githubusercontent.com/48538624/71785975-e177df80-2fe4-11ea-92ba-4a0776d73a88.png)

**Comment by lvnkmn** [comment]
I'm pretty sure this should be fixed in the latest code that's on the master branch of this repo. Can you try if this issue disappears when using that? If so, it would be a good idea for @cbpowell to create a release using that soon.

**Comment by cbpowell** [comment]
@lvnkmn hopefully the MarqueeLabel 4.0.1 release fixes it, that adds SPM back in and should also allows older Xcode versions.

**Comment by lvnkmn** [comment]
For now, this configuration works:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2656075/73833788-d514bb80-480a-11ea-93e3-2f0a9d03a479.png">

Looking forward to a release of that @cbpowell 🙂

**Comment by cbpowell** [comment]
@lvnkmn that release is actually already available. Is there anything more required on my end?

**Comment by lvnkmn** [comment]
[This commit](https://github.com/Daltron/NotificationBanner/commit/b9d9e7e344d5526be0cfc60c5c3f355f5afd9c21) in master solves the issue, but hasn't been released yet.

@cbpowell tagging that commit with **3.0.4** would solve our problems

**Comment by cbpowell** [comment]
Gotcha, I was making sure there’s nothing else needed on the MarqueeLabel side. I can’t help with tagging in this repo.

**Comment by lvnkmn** [comment]
@cbpowell Ah, didn't know that's your repo. Well in that case, what could also fix current issues is by undeleting the Xcode 11 branch. `NotificationBanner` **3.0.3** is still pointing to that branch and since that one doesn't exist SPM currently fails when using Symantic versioning.

@Daltron  Preferably I hope there will be a **3.0.4** tag for This commit soon.

**Comment by lvnkmn** [comment]
@cbpowell tagging the latest released commit with `xcode11` since tags are also seen as branches in SPM.
