### ISSUE TITLE
Haptic Feedback Crash

### ISSUE THREAD

**Issue by danlevy1** [Daltron/NotificationBanner#28]
I have a `NotificationBanner` appear on startup if the user is not connected to the internet. If the code is not called on the main thread, the app crashes with `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'ERROR: -[_UIFeedbackHapticOnlyEngine _deactivate] called more times than the feedback engine was activated'`. I fixed it by putting all of the `NotificationBanner` code in `DispatchQueue.main.async { }`

[A link to a StackOverflow post](https://stackoverflow.com/questions/40273911/uifeedback-haptic-engine-called-more-times-than-was-activated)

**Comment by Daltron** [comment]
@danlevy1 I'm going to close this as this is not an issue with NotificationBanner. When updating the UI, you should always be doing so on the main thread. This, when you are trying to show a banner, it should be on the main thread, thus, the haptic will automatically be called on the main thread as well.
