### ISSUE TITLE
Failed to load appWindow the app crashed

### ISSUE THREAD

**Issue by Ahmed-Masoud** [Daltron/NotificationBanner#284]
this happens when i show the banner with internet connection error based on a notification from Reachability this happens when the internet is manually turned off from control center at this point the pod failes to get the correct app window and fails

**Comment by darkandchoco** [comment]
Same here with a new project in Xcode 11 iOS 13, it has something to do with SceneDelegate when NotificationBanner is getting the current app window. Current window is nil since NotificationBanner is not able to get a current window that is active from scene delegate.

`    private let appWindow: UIWindow? = {
        if #available(iOS 13.0, *) {
            return UIApplication.shared.connectedScenes
                .first { $0.activationState == .foregroundActive }
                .map { $0 as? UIWindowScene }
                .map { $0?.windows.first } ?? UIApplication.shared.delegate?.window ?? nil
        }

        return UIApplication.shared.delegate?.window ?? nil
    }()`

**Comment by darkandchoco** [comment]
My workaround is to not call notification banner in app delegate but in view did appear in one of my main views:

`
private let reachability = try! Reachability()
private var banner: NotificationBanner?

private func configureReachability() {
        guard !isReachabilityConfigured else { return }
        
        reachability.whenReachable = { reachability in
            self.banner?.dismiss()
        }
        
        reachability.whenUnreachable = { [weak self] _ in
            guard let self = self else { return }
            if let banner = self.banner {
                banner.show()
            } else {
                self.banner = NotificationBanner(title: "No Internet Connection..", subtitle: nil, leftView: nil, rightView: nil, style: .danger, colors: nil)
                self.banner?.autoDismiss = false
                self.banner?.show()
            }
        }

        do {
            try reachability.startNotifier()
        } catch {
            print("Unable to start notifier")
        }
        
        isReachabilityConfigured = true
    }
`

**Comment by Surferdude667** [comment]
@darkandchoco Thank you so much! This totally fixed it! @Daltron
