### ISSUE TITLE
Showing notification banner makes 'custom' UIWindow disappear

### ISSUE THREAD

**Issue by wiencheck** [Daltron/NotificationBanner#285]
I have added another UIWindow on top of my app's main window and when NotificationBanner displays the window disappears, no matter what `.windowLevel` it has set. The code for window looks like this:

```
        searchWindow = UIWindow()
        searchWindow.windowLevel = .normal
        searchWindow.backgroundColor = .clear
        searchWindow.rootViewController = rootViewController
        searchWindow.makeKeyAndVisible()
```

If I set the .windowLevel to .alert the window doesn't disappear but the banners are not visible. I tried setting the .windowLevel to both .normal and .statusBar and added +1 but the issue still existed

**Comment by fukemy** [comment]
hi buddy, did u solved that?
