### ISSUE TITLE
Fatal error with: bannerPositionFrame.startFrame

### ISSUE THREAD

**Issue by EdwinJr13** [Daltron/NotificationBanner#286]
When I try to display the notification on a real device it shows that error:

Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

On this line:  

self.frame = bannerPositionFrame.startFrame

Help please.

**Comment by shikhil-sevenlakes** [comment]
Did we have any update on the fix?

**Comment by shikhilnuwal** [comment]
Do we have any update on the fix?

**Comment by krparakhiya** [comment]
Any update because i face same error.

**Comment by AlaaElrhmanArafa** [comment]
same issue

**Comment by gavrilaf** [comment]
Have the same issue. 
I use the Banner from SwiftUI so I don't pass the UIViewController, banner shows on the main window.

**Comment by gavrilaf** [comment]
I found my case reason. The application tries to show banner when a user cancels Google/Fb authentification, so the current scene has foreground inactive state and NotificationBanner couldn't retrieve the window.

It happens here:
```
if #available(iOS 13.0, *) {
            return UIApplication.shared.connectedScenes
                .first { $0.activationState == .foregroundActive }
                .map { $0 as? UIWindowScene }
                .map { $0?.windows.first } ?? UIApplication.shared.delegate?.window ?? nil
        }
```

Dirty workaround - show notification with delay. 
Or add support for pending notifications and show notifications depends on application state. But it isn't the question for the library.

**Comment by sandeep9607** [comment]
please check this from author
https://github.com/Daltron/NotificationBanner/pull/295#issuecomment-623175359

**Comment by AlexeyLazukinIOS** [comment]
had the same malfunction, ios 13.4.1, a very common scenario
