### ISSUE TITLE
banner.autoDismiss is not available in the pod version

### ISSUE THREAD

**Issue by syedtariq2013** [Daltron/NotificationBanner#29]
Trying to use banner.autoDismiss and it was not recognized. I checked the code that was installed by pod and it does not have any reference to autoDismiss. It is in the github version

**Comment by Daltron** [comment]
Hi @syedtariq2013! 😄 Sounds like you don't have the up to date source files. Try running `pod update NotificationBannerSwift` and that should fix your issue.

**Comment by syedtariq2013** [comment]
Hi Daltron - Pods pulls in v1.2.0 which is quite old. Even after updating the repo pod still picks up v1.2.0. I realize I can always copy 1.3.2 but using pods is so much more convenient. It is possible I need to refresh my pods knowledge.

BTW, it is a beautifully written and very useful library.

**Comment by Daltron** [comment]
@syedtariq2013, what does your Podfile look like? Are you telling it to specifically pull down 1.2.0? If you are not, try updating your specs repo by running the following command `pod repo update`. After that is completed, then try running `pod update NotificationBannerSwift` and see if version 1.3.2 is downloaded.

**Comment by syedtariq2013** [comment]
Hi Daltron - I resolved it by asking specifically for 1.3.2 in the Podfile. (pod 'NotificationBannerSwift', '~> 1.3.2’). This is completely ok as far as a procedure is concerned.

Thank you for your help.

**Comment by Daltron** [comment]
@syedtariq2013 Glad to hear! Enjoy! 😄
