### ISSUE TITLE
Title/subtitle do not appear when right view is set

### ISSUE THREAD

**Issue by haukurhal** [Daltron/NotificationBanner#293]
There is no problem when I only show the left view. However when I try to show the right view, it appears on top of the left view and the text doesn't show. Like so:

![image](https://user-images.githubusercontent.com/30110854/76874313-ecfa4900-6866-11ea-8948-1c516e8d31e5.png)

It may not be too obvious but there is a right arrow (chevron) on top of the leftView, and no text is visible.

This is when I only display the left view:

![image](https://user-images.githubusercontent.com/30110854/76874530-38145c00-6867-11ea-9243-8e9d6ede1f30.png)

Any ideas?

**Comment by maxmika** [comment]
Yep, same here.

**Comment by psalzAppDev** [comment]
The constraints for the right view are not correct. I will submit a pull request with a fix.
