### ISSUE TITLE
[Question] How to decrease the time banner stays on. 

### ISSUE THREAD

**Issue by alokc83** [Daltron/NotificationBanner#308]
I have been trying to figure out if I can reduce the time that the banner stays on. 
I couldn't find anything. Can anyone help me, please

**Comment by roteirod** [comment]
Hi there! I just do it this way: 
```
banner.show()
DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
banner.dismiss()
}
```

**Comment by roteirod** [comment]
Actually, it's like this:
`banner.duration = 2`
Just found it :D
