### ISSUE TITLE
No support for UIVisualEffectView?

### ISSUE THREAD

**Issue by scruff311** [Daltron/NotificationBanner#313]
I have a `customView` that is of type `UIVisualEffectView`, but when I add it as a `customView` to the banner, the background is not getting the blur affect applied. If I add the same view directly to my `viewController.view`, the blurring works as expected. Is there some workaround to get these to work within the banner?

**Comment by fukemy** [comment]
how did u solved that? same problem here

**Comment by m-ricca** [comment]
same for me
