### ISSUE TITLE
extension UIWindow issue

### ISSUE THREAD

**Issue by IM-TNinja** [Daltron/NotificationBanner#315]
Hello! You using the height & width in 'UIWindow' extension. It's an issue for the projects which have their own UIWindow extension for this properties and the project won't compile.

**Comment by kylebrowning** [comment]
This is still an issue why does it keep getting closed?

**Comment by IM-TNinja** [comment]
Hey @kylebrowning, it's still not solved... 
In my project, I manage to rename width, height properties to nbsWidth, nbsHeight, to fix this issue and notify all my team members to not update this pod.

**Comment by kylebrowning** [comment]
@IM-TNinja I fixed it here, #340
