### ISSUE TITLE
delegates?

### ISSUE THREAD

**Issue by Marlon-Monroy** [Daltron/NotificationBanner#32]
Would be nice to know when the alert has been dismiss or is about to show.

**Comment by Daltron** [comment]
Hi @Marlon-Monroy! 😄  I think this is a great idea. I'll add it to the next release! 👍

**Comment by Daltron** [comment]
@Marlon-Monroy Included in [v1.4.0](https://github.com/Daltron/NotificationBanner/releases/tag/1.4.0) release! 🎉
