### ISSUE TITLE
Update readme regarding to changes to `windowLevel` since iOS 13

### ISSUE THREAD

**Issue by HenryQuan** [Daltron/NotificationBanner#325]
# windowLevel
Since iOS 13, `windowLevel` won't place anything on top of the `system status bar`.
# Potential fixes
- Make the view longer as mentioned in #240 
- Hide the status bar at the root controller and then, display the alert normally to make it `on top`

This repo has almost 4k stars so I think the `README` should be updated to reflect this problem and also, potential fixes.

**Comment by Daltron** [comment]
Hi @HenryQuan! Feel free to open up pull requests for any issues you see!
