### ISSUE TITLE
SwiftUI custom view support

### ISSUE THREAD

**Issue by macoapps** [Daltron/NotificationBanner#327]
Hi,
I'm using your awesome library which is currently based on UIKit. I plan to move to SwiftUI, and still want to keep your library.
I did some tests to use SwiftUI views as custom views, using UIHostingController, but the layout become weird.
I think that this the SwiftUI view bounds are computed AFTER the banner appears, but not sure.
Do you plan to support SwiftUI in the future releases ? 

By the way, thank you for your work. It's really helpful and really well done, so I'll continue to sue even if I need to keep UIKit for banners only !

Best regards

**Comment by Daltron** [comment]
Hi @macoapps! SwiftUI is still a long ways away before coming primetime. Thus NotificationBanner has no immediate plans to support SwiftUI currently but that could most certainly change in the future when SwiftUI becomes a little bit more relevant.

**Comment by ThePredators** [comment]
I think we can consider this library dead by now, since no support fro SwiftUI :/ 

By the way i used this since 2023 : [SwiftMessages](https://github.com/SwiftKickMobile/SwiftMessages)
