### ISSUE TITLE
Swift package for 3.0.4?

### ISSUE THREAD

**Issue by Preston-Landers** [Daltron/NotificationBanner#332]
Hello, 

First of all, thank you for your excellent work on this very useful library.

I was using version 2.5.1 for a while then I updated to 3.0.2 which is the latest available Swift package. Then I noticed I was affected by a bug where queued banners forget their position. It looks like there's a fix in 3.0.4 for this, from this commit:

96ff93f0d1e599527b361d856d0b403f27736762

Unfortunately it looks like the Swift package hasn't been updated and is still on 3.0.2. Would you mind publishing a new Swift package of 3.0.4? Thank you!

**Comment by Daltron** [comment]
Hi @Preston-Landers! I just released a new CocoaPods `3.0.5` version. I'm currently not familiar with how to publish a new Swift package. Would you mind submitting a PR for this? Thanks! 😄

**Comment by Preston-Landers** [comment]
Actually, for my purposes, what I really needed was the CocoaPods update, so I think I'm good now.

Apologies for getting my terminology wrong. I'm pretty new to the world of Swift and ObjC. I was not especially aware of the distinction between CocoaPods and the Swift Package Index. While adding this package to SPI may indeed be a worthy goal, at this point I have little idea how to accomplish it and don't particularly need it myself. 

Thanks again!
