### ISSUE TITLE
Broken on iPhone 12 pro

### ISSUE THREAD

**Issue by dweizhao** [Daltron/NotificationBanner#334]
It seems that the following code is broken on iPhone 12 Pro at least. (Didn't try other iPhone 12s)

    class func isiPhoneX() -> Bool {
        if UIDevice.current.userInterfaceIdiom != .phone {
            return false
        }
        return UIScreen.main.nativeBounds.height == 2436 // on iPhone 12 Pro, it's 2536
    }

**Comment by zinwalin** [comment]
same here. need help

**Comment by FunkyHotDog** [comment]
For me the banner won't show on iPhone X on a real device, but when I use simulator it works fine 🤔 I wonder if this is the underlying issue.
