### ISSUE TITLE
Swift package for 3.0.6

### ISSUE THREAD

**Issue by dregatos** [Daltron/NotificationBanner#337]
Hey @Daltron,

Could you please release a new version for the latest available tag (3.0.6)? This way, it would be possible to integrate the last version of this awesome framework through Swift Package Manager using the tag instead of the commit hash.

In case you are not familiarized with SPM, you only need to [edit](https://github.com/Daltron/NotificationBanner/releases/tag/3.0.6) the latest tag and assign it a title to make it an official release.

Thanks a lot for your work!!

**Comment by Daltron** [comment]
Hi @dregatos I just created a release for this! Please let me know if that didn't work! Thanks for your kind words! 😁

**Comment by dregatos** [comment]
Thanks a lot, @Daltron. It works!!
