### ISSUE TITLE
Multiline subtitles

### ISSUE THREAD

**Issue by kylemay-gridstone** [Daltron/NotificationBanner#34]
I've read PR #14, but I think there's an alternate solution by offering a property or something like `useMarquee` and using a standard UILabel. Unfortunately at the moment I'm going to have to use a different library because I need multiline.

**Comment by Daltron** [comment]
Hi @kylemay-gridstone! 😄 Sorry there is no multiline subtitles at this time. As more and more people are starting to request it, it is probably going to be one of the next features I support when I have the time to develop it. Until then, I encourage you to use whatever library best fits your needs. Thanks!
