### ISSUE TITLE
StatusBarNotificationBanner not showing title.

### ISSUE THREAD

**Issue by jazz-mobility** [Daltron/NotificationBanner#347]
Hi,

First of all thanks for this great framework. I am trying to use the `StatusBarNotificationBanner` in my app but somehow it is not showing me the title. Here is my code.

```
let banner = StatusBarNotificationBanner(title: "Please check your network connection", style: .danger)
banner.autoDismiss = false
banner.titleLabel?.text = "Please check your network connection"

banner.show()
```

Can you please let me know what I am missing here?

**Comment by DarkSatyr** [comment]
Try to show it on viewDidApper of your root controller
