### ISSUE TITLE
MAC Catalyst support

### ISSUE THREAD

**Issue by perbrondum** [Daltron/NotificationBanner#349]
Banner title line is overlapping with window title.

**Comment by CMiller3** [comment]
Hot fix: 

After declaring a FloatingNotificationBanner, I was able to change the position by editing the banner.frame after .show

`let banner = FloatingNotificationBanner(title: title, subtitle: subtitle, style: style)
banner.show(queuePosition: .front, bannerPosition: BannerPosition.top, queue: .default, on: nil, edgeInsets: UIEdgeInsets(top: 5, left: 5, bottom: 5, right: 5), cornerRadius: 5, shadowColor: .black, shadowOpacity: 0.5, shadowBlurRadius: 5, shadowCornerRadius: 5)

// LINE OF NOTE:
banner.frame = CGRect(origin: YOUR POINT, size: YOUR SIZE)`

**Comment by logansease** [comment]
banner.show()
            
            #if targetEnvironment(macCatalyst)
            banner.frame = CGRect(x: banner.frame.origin.x, y: banner.frame.origin.y + 40, width: banner.frame.size.width, height: banner.frame.size.height)
            #endif
