### ISSUE TITLE
NotificationBanner not showing in new SpriteKit app

### ISSUE THREAD

**Issue by dsarfati** [Daltron/NotificationBanner#35]
I'm trying to show a welcome message when my SpriteKit game opens. I tried to use the example NotificationBanner in the `override func viewDidLoad()` of the GameViewController, but nothing shows up. I discovered that if I have 2 banners show, then the 2nd one will show up after a delay (~5sec). Im assuming that this delay is due to the 1st one being shown. How should I deal with this? Call it from a different place within my initial view controller?

```
let banner = NotificationBanner(title: "Welcome back!", subtitle: "We are watching...", style: .success)
        banner.show()
        
let banner2 = NotificationBanner(title: "Welcome back again!", subtitle: "We are watching you too...", style: .success)
        banner2.show()

```

**Comment by Daltron** [comment]
Hi @dsarfati! 😄 Put your banner code in the view controller's viewDidAppear method and I bet that fixes your problem. Since viewDidLoad is called not when the view controller's view has yet to appear , it doesn't make since to show a banner just quite yet. Let me know if that helps!

**Comment by dsarfati** [comment]
Thanks for the info, will definitely give that a try. I figured it was in the wrong part of the lifecycle.

**Comment by dsarfati** [comment]
That seems to have done the trick. Thanks for the quick response!!

**Comment by Daltron** [comment]
@dsarfati awesome! Thanks for reporting back!
