### ISSUE TITLE
Crashes while screen mirroring with Airplay v1 [BaseNotificationBanner.swift:380]

### ISSUE THREAD

**Issue by majid701** [Daltron/NotificationBanner#350]
I found an issue with the library it crashes when a notification banner is shown while the phone is casting the screen via Airplay. It seems to happen only with Airplay version 1. I experienced the crash while using Reflector 3 which uses the older version of Airplay. It works completely fine with Reflector 4 which uses the newer version of Airplay.

stack trace:
```
Crashed: com.apple.main-thread
0  NotificationBannerSwift        0x103b5bb30 BaseNotificationBanner.show(placeOnQueue:queuePosition:bannerPosition:) + 380 (BaseNotificationBanner.swift:380)
1  NotificationBannerSwift        0x103b65a74 NotificationBannerQueue.addBanner(_:bannerPosition:queuePosition:) + 78 (NotificationBannerQueue.swift:78)
2  NotificationBannerSwift        0x103b5b234 BaseNotificationBanner.show(placeOnQueue:queuePosition:bannerPosition:) + 374 (BaseNotificationBanner.swift:374)
3  NotificationBannerSwift        0x103b5af34 BaseNotificationBanner.show(queuePosition:bannerPosition:queue:on:) + 337 (BaseNotificationBanner.swift:337)
```

Is this something that can be fixed in the library or the problem is with Airplay? Looks like the frame of the screen is changed while screen mirroring is active. Any suggestions? I am to open to contribute with a PR.

NotificationBannerSwift version: 3.0.6
It worked completely fine with older version 1.6.3
Tested on iPhone 11, iOS: 14.4.2

**Comment by MRiOSRohit** [comment]
@majid701 Do You find the solution for this issue?

**Comment by majid701** [comment]
@MRiOSRohit I downgraded the library version back to 1.6.3.

**Comment by prachi-simformsolutions** [comment]
anyone find the solution?
