### ISSUE TITLE
When your project install some dev tool like 'DoraemonKit' you should uninstall it.

### ISSUE THREAD

**Issue by xysT2W** [Daltron/NotificationBanner#353]
Just warning for others.
It cause the framework can't fetch the suitable window.

**Comment by shgew** [comment]
What do you mean?

**Comment by xysT2W** [comment]
> What do you mean?

'DoraemonKit' will create a window to hold a float button on the screen.
It cause some error on property: 'appWindow' in 'BaseNotificationBanner.swift' file.
When I Install the 'DoraemonKit' on my App, I get a 44*44 size window from 'appWindow'.

**Comment by shgew** [comment]
Got you, thanks
