### ISSUE TITLE
SPM in Xcode 13: 'shared' is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by JMCPH** [Daltron/NotificationBanner#358]
When building with Xcode 13 beta 3 I get the following error:

`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

**Comment by manucheri** [comment]
I also stumbled upon this when updating to the latest beta. This PR makes it compile again for me: https://github.com/Daltron/NotificationBanner/pull/361
