### ISSUE TITLE
Right to left error 

### ISSUE THREAD

**Issue by Yoloabdo** [Daltron/NotificationBanner#36]
Hello, is it available to view right to left text and make all view from right to left?

**Comment by Daltron** [comment]
Hi @Yoloabdo! 😄 To answer the first part of your question:

```swift
banner.titleLabel?.type = .right
```
That will scroll the text from right to left.

If you could explain a little bit more for the second part of your question, it would be greatly appreciated as I don't know exactly what you are asking. Thanks!

**Comment by Daltron** [comment]
Please feel free to reopen if this doesn't solve your issue! Thanks!

**Comment by Yoloabdo** [comment]
I tried to set it but didn't work, RTL languages support is what I meant, the text is always on left, thanks

**Comment by Daltron** [comment]
@Yoloabdo I'm not quite sure what you mean. Could you elaborate more or provide a detailed picture explaining the desired functionality you want please?

**Comment by VictorApeland** [comment]
Languages like Arabic read right to left, not left to right. 
![screen shot 2017-08-02 at 15 18 24](https://user-images.githubusercontent.com/28315844/28875442-e02daa1a-7795-11e7-8aa9-bcbb81509e91.png)

**Comment by Daltron** [comment]
@VictorApeland Thanks for explaining this. As of right now, I do not plan on supporting this but that could change if more people want this capability.

Thanks! 👍
