### ISSUE TITLE
Floating banner is not working

### ISSUE THREAD

**Issue by afern247** [Daltron/NotificationBanner#362]
Hi! I just discovered this beautiful package and tried this:

```
let banner = FloatingNotificationBanner(title: "...", subtitle: "....", style: .info)
banner.haptic = .medium

banner.show()
```

but the banner style shows like the default, not in a floating view, am I doing something wrong?

I'm using XCode 13, swift 5.5, swiftui 3.0

Thanks

**Comment by Cam4dams** [comment]
+1

**Comment by Mahmoud-Abdelwahab** [comment]
+1

**Comment by ananevam** [comment]
It works if you'll add such cornerRadius
banner.show(cornerRadius: 16)
