### ISSUE TITLE
Allow offset?

### ISSUE THREAD

**Issue by scottcc** [Daltron/NotificationBanner#37]
I have a second use case where I need the notification to appear below a view (which has a search bar). I've tried using a container view (essentially a dummy view) to then pass the `on viewController:` optional `UIViewController` parameter - it has a rather funny effect of animating from where I want, but goes up instead of down and disappears before it finishes its animation.

I'm using a custom view for that case, if that matters.

So - either I need the `bannerPositionFrame: BannerPositionFrame!` variable to be exposed, or some way to set an offset (from the top, but you could imagine it just based on whatever is passed for the `bannerPosition: BannerPosition!` variable.

Lastly - not that it matters here, but just wondering if the `bannerPosition` and `bannerPositionFrame` variables should be explicitly unwrapped optionals? They do start out as `nil` (indeed you check for that in the start of `BaseNotificationBanner.show()`. Of course, they're private at the moment so the class is free to tell me off; they're it's business not mine.

Thanks again - great library!

**Comment by Daltron** [comment]
Welcome back @scottcc! 😄  If you quickly mock up what you are wanting via photoshop, paint, etc... to give me a visual understanding, I should be able to better assist you. 😄 It doesn't have to be anything fancy!

To answer the second part of your question, no I do not believe it makes sense to make those variables explicitly unwrapped optionals. I know that when I access them, that they are going to exist. You should use optionals in your code when you are unsure wether or not they will have values assigned to them before you pass them off or use them for something else. However, if you disagree, I'm open to a good discussion! 👍

**Comment by scottcc** [comment]
Actually - I was suggesting they might be just plain optionals - Due to my debouncing I found one crash (my error) where I called `dismiss()` on a banner I'd not called `show()` - that code line hits one of those explicitly force-unwrapped vars and dies. Anyway - you want to keep them explicit, I'm ok with that. 

As for what I'm (thinking) would be good would be an offset (default of zero) `CGFloat` that could be applied to the frame assumed. That way I could specify something that would adjust both the start and end frames. Something I could use with something like this:

![offsetmockup](https://user-images.githubusercontent.com/225380/28037434-44a435a0-6589-11e7-8113-f119702a5e07.png)

**Comment by Daltron** [comment]
@scottcc thanks for the picture, that completely helps me figure out what you are wanting. I might have to think more about the best way to implement this as I assume you are going to want the banner to animate in from behind that search bar? The problem with this is that search bar will need to be moved to the front of the subview hierarchy of your view before the banner shows or else the banner will animate over the searcher which will be a bad user experience. That will have to be done manually by the programmer. Adding an offset may be the cleanest option for this feature.

**Comment by scottcc** [comment]
Yeah, I was thinking about the animation aspects. I might try out something by having the view height animate from 0 -> target as opposed to animating the y position entirely. I'll let you know how it works out (or doesn't).

**Comment by scottcc** [comment]
Ok - I seem to have a working example on a dev branch at the moment, going to move my Podfile to that and see if it'll do what I need: https://github.com/scottcc/NotificationBanner/tree/dev
