### ISSUE TITLE
Swift Package support?

### ISSUE THREAD

**Issue by haitaox** [Daltron/NotificationBanner#372]
just wondering if SPM is coming :)

**Comment by theedov** [comment]
this repo supports spm.

**Comment by theedov** [comment]
this library supports SPM.

**Comment by alexookah** [comment]
close this issue @haitaox

**Comment by styrken** [comment]
Maybe add a section to the README at some point 👍

**Comment by alexookah** [comment]
Now this issue can be closed @Daltron
