### ISSUE TITLE
The banner disappears behind the dynamic island for iPhone 14 Pro

### ISSUE THREAD

**Issue by materik** [Daltron/NotificationBanner#394]
![Simulator Screen Shot - iPhone 14 Pro - 2022-09-15 at 16 17 32](https://user-images.githubusercontent.com/2392010/190428522-341bf796-4941-438e-8e2f-172751ed3738.png)

Is there a way to increase the top padding or choose another style that fixes it today or will it require an update?

**Comment by Daltron** [comment]
@materik this should be handled internally by the library to prevent this from happening if the dynamic island is present. I don't currently have time to work on this but would gladly accept a PR!

**Comment by Maxim-Inv** [comment]
@materik I've pushed the PR to fix it, until it will be accepted you can use this fix in my fork - https://github.com/Maxim-Inv/NotificationBanner

**Comment by materik** [comment]
Awesome. Thanks @Maxim-Inv

**Comment by materik** [comment]
Related PR #395
