### ISSUE TITLE
iPhone Dynamic Island

### ISSUE THREAD

**Issue by MalcolmnDEV** [Daltron/NotificationBanner#401]
The banner does not account for the new dynamic island
<img width="420" alt="Screenshot 2022-11-14 at 09 13 14" src="https://user-images.githubusercontent.com/36816789/201620957-be3f0308-dace-439a-9ecf-22a1c661461e.png">

**Comment by vivek-mittal** [comment]
@MalcolmnDEV Is there a workaround? The PR has been open for over a month now.
