### ISSUE TITLE
iOS Minimum Version 9.0 + Tag 

### ISSUE THREAD

**Issue by morgan-legal** [Daltron/NotificationBanner#41]
Hi Dalton,

First of all, kudos on the lib, easy to use and does everything that I need! 

I'm creating an issue for the minimum iOS version of the project which is actually 9.3 instead of 9.0 (as documented in the readme). I've forked and tested it and it won't create any issue. 

If you do change the minimum iOS version, is it possible to create a new tag (1.4.1). I'm using Carthage and I'm not a huge fan on pointing directly to the master branch as mentioned it in the readme. 

Thank again for everything! 
Morgan

**Comment by Daltron** [comment]
Hi @morgan-legal! 😄 Feel free to open a PR request if your wanting this feature. I'm not familiar with Carthage and didn't setup NotificationBanner to work with Carthage so there must be a minimum deployment target of 9.3 somewhere.  I know the minimum for CocoaPods is in fact 9.0. Feel free to change it to 9.0 if your able to get it to work that low 👍
