### ISSUE TITLE
Request for updated iOS SDK version with the xcprivacy manifest

### ISSUE THREAD

**Issue by sakshibala-halodoc** [Daltron/NotificationBanner#429]
Subject: We need to incorporate the xcprivacy manifest into our app . Starting March 13, Apple will send notifications when uploading builds to the App Store, and this will become mandatory from May 1. All the SDKs used in our app needs to incorporate the xcprivacy manifest.
Reference: https://developer.apple.com/news/?id=3d8a9yyh

Actions needed: We need the compatible xcprivacy manifest version IOS SDK with xcprivacy manifest. We are expecting a seamless upgrade by upgrading to the latest version.

**Comment by yasiraliraj** [comment]
Hello Notification Banner Team,

I hope this message finds you well. I would like to draw your attention to an important update required by the App Store. Starting May 1, 2024, a privacy manifest will be mandatory for all apps. Given the ongoing development and support for your SDK, integrating this feature would be highly beneficial for ensuring compliance with the new App Store guidelines. This addition would greatly help developers like us in continuing to provide seamless services through our applications. We appreciate your attention to this matter and look forward to any updates you can provide.

Thank you for your continued support.

**Comment by phoney** [comment]
There already are two PRs.

https://github.com/Daltron/NotificationBanner/pull/426
https://github.com/Daltron/NotificationBanner/pull/428

These update the dependencies but don't seem to add a Privacy Manifest for NotificationBanner itself.

**Comment by phoney** [comment]
@Daltron Thanks for the updates. While you updated the podspec file and added the 4.0.0 tag CocoaPods still thinks the current version is 3.2.1. I guess you still need to register the update with Cocoapods.

**Comment by ape992** [comment]
`pod 'NotificationBannerSwift', :git => 'https://github.com/Daltron/NotificationBanner.git'`

I used this method temporarily.

**Comment by phoney** [comment]
I'm using this temporarily

```pod 'NotificationBannerSwift', :git => 'https://github.com/Daltron/NotificationBanner.git', :commit => '9550d28f111652614e3957e754cde0d7b349bc43'```
