### ISSUE TITLE
Adjust subtitle font to fit 

### ISSUE THREAD

**Issue by gsmeros** [Daltron/NotificationBanner#43]
I have a relatively big subtitle but trying to resize the 'MarqueeLabel' wont work:
```
self.adjustsFontSizeToFitWidth = true
self.minimumScaleFactor = withScale
self.numberOfLines = numberOfLines
```

Can I change the font of the label so it can fit my text in one or two lines ? Thanks

**Comment by Daltron** [comment]
Hi @gsmeros! 😄 `adjustsFontSizeToFitWidth` and `self.numberOfLines` won't work with MarqueeLabel since it scrolls. I might add support for multiple line subtitles in the future but am correctly locked down with other development commitments. You can keep up with the status here #34

**Comment by riclage** [comment]
@Daltron Would you be open to a contribution to add multi-line support? And how do you think the implementation should be done? I could make a PR for it once we agree on an approach.
