### ISSUE TITLE
Remove banners added to the Queue

### ISSUE THREAD

**Issue by ashokkumars** [Daltron/NotificationBanner#44]
There should be a way we should be able to remove the banners lined up in the BannerQueue. This is in consideration that, I added some items to the queue and I have another notification coming up, which will take highest priority and displaying the banners in the queue is of no use. I've created a patch file as well with the necessary methods. 

You can access the new methods in two ways.

1. If there is a new banner with highest priority to be displayed, create the banner using the following way. And using the same banner instance, call the clearBannerQueue() method.

_let banner = StatusBarNotificationBanner(title: "Highest priority message")
banner.clearBannerQueue()
banner.show(on: self)_

2. If you just wanted to clear the bannerQueue, you can use the NotificationBannerQueue instance and clear them

_NotificationBannerQueue.default.clearBannerQueue()_

Please find the attached patch file. This patch file was created on top of the Commit numbered **2c41cf4**
[patch.diff.zip](https://github.com/Daltron/NotificationBanner/files/1196172/patch.diff.zip)

**Comment by Daltron** [comment]
Hi @ashokkumars! 😄 Are you familiar with the `queuePosition` property when calling `banner.show()`? Or are you stating that you may have a notification that makes all other banners on the queue **completely** irrelevant, thus they should never be shown?

**Comment by ashokkumars** [comment]
Hey @Daltron. I am aware of the **queuePosition**. But lets consider this case. I am calling 3 or 4 webservices in a class and all of them for some reason gets failed. All the error messages will be added to a queue. But before all banners gets shown (from the queue), if the device network gets disconnected, I need to show another banner which is for the network disconnect. After this banner is shown, showing webservice error banners is of no use. So, I felt like, there should be a method, which should allow me to clear the existing banner queue. This is just one use case, there can be many other cases as well.

**Comment by Daltron** [comment]
@ashokkumars Ok perfect, thanks for explaining! I just added this functionality to the [v1.4.1](https://github.com/Daltron/NotificationBanner/releases/tag/1.4.1) release! 🎉

**Comment by firvorski** [comment]
Hi, it looks like removeAll() is not there any more in 1.4.2. I also thought it would be quite useful to be able to remove all queued notifications. Is there a chance it will be put back or should we stick with 1.4.1 for now?

**Comment by Daltron** [comment]
Hi @firvorski! 😄 This was an accidental mistake! It is now included and public in the 1.4.3 version! Thanks for bringing this to my attention! 👍

**Comment by firvorski** [comment]
You da man! 
Thanks a lot.
