### ISSUE TITLE
iOS 8 Support

### ISSUE THREAD

**Issue by kuyazee** [Daltron/NotificationBanner#46]
Will this project have iOS 8 support in the future?

**Comment by Daltron** [comment]
Hi @kuyazee! 😄 I have zero plans on supporting iOS 8 unfortunately. There just isn't enough users on iOS 8 to make it worthwhile. According to Apple, less than 3% of iOS users use a version below iOS 9. I hope that is understandable! Thanks! 👍

**Comment by kuyazee** [comment]
Thank you for the very fast response, much appreciated 💯
