### ISSUE TITLE
I alreade have SnapKit, how to install it by PODS?

### ISSUE THREAD

**Issue by bizibizi** [Daltron/NotificationBanner#47]
[!] Unable to satisfy the following requirements:

- `SnapKit (~> 3.0.0)` required by `Podfile`
- `SnapKit (= 3.0.2)` required by `Podfile.lock`
- `SnapKit (~> 3.2.0)` required by `NotificationBannerSwift (1.0.0)`

**Comment by Daltron** [comment]
Hi @bizibizi! 😄 You need to remove the SnapKit dependency in your Podfile. What that log is telling you is that NotificationBanner requires version 3.2.0 but you have specified in your Podfile to use version 3.0.0.
