### ISSUE TITLE
iPhoneX safe area not respected.

### ISSUE THREAD

**Issue by JoniVR** [Daltron/NotificationBanner#49]
Hi Daltron! 

You are probably already aware of this issue, but I thought it wouldn't hurt to just post it here.
So I tested this library for my project on the iPhone X, and the notifications don't seem to respect the safe area, causing it to be hidden behind the notch. 

I'd fix it myself but I'm not that good with SnapKit and code constraints in general. 

Thanks for your great work! 

Best regards, 
Joni

**Comment by Daltron** [comment]
Hi @JoniVR! Thanks for reporting this! I was not aware of this. I will look into this. In the meantime, if you could post a picture, that would be greatly appreciated!

**Comment by JoniVR** [comment]
Sure, no problem. 😁

![example](https://user-images.githubusercontent.com/7591717/30511669-71365c26-9ade-11e7-81fe-9cb9f61baeed.jpeg)

**Comment by jenjia** [comment]
Let me add - because it may be related - that also for iOS 11 the StatusBarNotificationBanner appears beneath the NavigationBar.

**Comment by Daltron** [comment]
@jenjia I am not able to reproduce. Are you sure your not showing the banner on a view controller? That would cause it to appear beneath the navigation bar.

**Comment by Daltron** [comment]
@JoniVR I'm still thinking about the best way to go about this. Status bar notifications are basically useless now because that safe space covers it up. Still kind of blows my mind that Apple did this as it is such poorly designed in my opinion. We'll find away around it though 👍

**Comment by Daltron** [comment]
@JoniVR would you be opposed to these implementations in any way?

<img width="399" alt="screen shot 2017-09-19 at 8 57 11 am" src="https://user-images.githubusercontent.com/9689335/30596035-9b4dea60-9d18-11e7-9236-7431a3e72882.png">
<img width="405" alt="screen shot 2017-09-19 at 8 56 35 am" src="https://user-images.githubusercontent.com/9689335/30596040-9cf00baa-9d18-11e7-9415-685162e1246f.png">

**Comment by JoniVR** [comment]
@Daltron Looks fine to me 👌🏻 
I would also test to see if banners with images don't get cut off by the rounded corners. If you are using the SafeAreas Apple provided it should be fine though :) 

I'm personally not sure what to think about it, I think they should've just blacked out the statusbar and let it always be visible (unless the dev disables it). But whatever, so be it, I guess there's a lot of creative possibilities with it too😜

Also, I'd gladly help you test it if you want to, just let me know and I'll find some time 🙂
As always, thanks for all the effort you put into this 👍

**Comment by Daltron** [comment]
@JoniVR Included in [v1.4.4](https://github.com/Daltron/NotificationBanner/releases/tag/1.4.4) release! 🎉 Thanks again for bringing this to my attention!
