### ISSUE TITLE
SnapKit v4 for Swift 4

### ISSUE THREAD

**Issue by FunProject** [Daltron/NotificationBanner#53]
Hello,
Please update SnapKit dependency to v4.0 to be Swift 4.x and iOS 11 compatible.
Right now I cannot build the app.
Thanks

**Comment by Daltron** [comment]
Duplicate of #51

**Comment by Daltron** [comment]
@FunProject Swift 4 support is now available in [v1.5.0](https://github.com/Daltron/NotificationBanner/releases/tag/1.5.0) release! 🎉

**Comment by FunProject** [comment]
Great! Thanks 👍
