### ISSUE TITLE
Unexpectedly found nil when setting up banner

### ISSUE THREAD

**Issue by AAAstorga** [Daltron/NotificationBanner#54]
Hello,

I am using Reachability with your NotificationBanner. For example, when there is no internet, I am displaying a status bar notification saying "No Internet Connection". I am facing this very odd bug.

At the top of my ViewController I declare a variable
```swift
var isBannerShown = false
var banner: StatusBarNotificationBanner?
```
I also have a function that fires when reachability changes. It will go off when you go from online -> offline and vice versa.

```swift
    func reachabilityChanged(note: Notification) {
        if banner == nil {
            banner = StatusBarNotificationBanner(title: "No Internet Connection")
            banner?.autoDismiss = false
        }
        let reachability = note.object as! Reachability
        switch reachability.connection {
            case .none:
                isBannerShown = true
                banner?.show(queuePosition: .front, on: self)
                self.isNetworkDown = true
                self.sectionIndexes = [:]
                self.tableViewIndexController.tableViewIndex.reloadData()
                self.searchBar.isUserInteractionEnabled = false
                self.sections = []
            case .cellular, .wifi:
                if isBannerShown {
                    print("Banner is currently displayed")
                    banner?.dismiss()
                    isBannerShown = false
                }
                sections = createSections()
        }
    }
```

This type of behavior is causing the banner to crash. I have no idea why. When I go and comment out

```swift
bannerPositionFrame = BannerPositionFrame(bannerPosition: bannerPosition,
                                                  bannerWidth: appWindow.frame.width,
                                                  bannerHeight: bannerHeight,
                                                  maxY: maximumYPosition())
```

everything works as normal. The app I am working on doesn't deal with different orientations. It is always in vertical mode.

Any suggestions on why this is happening?

<img width="1037" alt="screen shot 2017-09-24 at 2 44 09 pm" src="https://user-images.githubusercontent.com/15990084/30785591-e263b322-a136-11e7-8c44-a4085c983c2d.png">

**Comment by Daltron** [comment]
Hi @AAAstorga! 😄 Your code looks fine. Does this happen every time you run your project? This sounds like it might be a derived data issue. If you could delete your derived data folder and report back, that would greatly appreciated! 👍

**Comment by Daltron** [comment]
@AAAstorga I just pushed a [1.5.1](https://github.com/Daltron/NotificationBanner/releases/tag/1.5.1) release that you can try out. I still think derived data has something to do with your scenario since your project is locked in portrait mode, however this release fixes an edge case around the orientation notification.

**Comment by AAAstorga** [comment]
@Daltron Thank you so much! I tried deleting derived data, but no luck. I just saw you released 1.5.1 but my project is on Swift 3.2. Is the only way to get this change is to update my project to Swift 4?

Thanks!

**Comment by Daltron** [comment]
@AAAstorga Swift 4 and Swift 3.2 are interchangeable with each other. Just include this at the bottom of your podfile:

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['NotificationBannerSwift', 'SnapKit', 'MarqueeLabel'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```
In case your wondering, NotificationBanner uses SnapKit and MarqueeLabel as dependencies so they need to built in swift 4.0 as well!

**Comment by AAAstorga** [comment]
Ahh! This fixed it. Thank you so much for this! Teamwork is the best work. I appreciate it the help! Awesome pod by the way

**Comment by mitulmarsonia** [comment]
HI @Daltron ,

I'm getting same issue in swift 3.2. I'm using pos ->  pod 'NotificationBannerSwift', '~> 1.4.4'

Can you please help me out ?

**Comment by Daltron** [comment]
Hi @mitulmarsonia! 😄 You will see this issue occur if you are using version 1.4.4

You should change that tag to 1.5.2 and then add the `post_install` function that I mentioned a few comments above and you should be good to go! Let me know if you need any help.

**Comment by mitulmarsonia** [comment]
HI @Daltron ,

When i try to install pod 1.5.2 that time SnapKit pod version also update 4.0.0 it. SnapKit pod version 4.0.0 for swift 4 so getting error for swift for i need swift 3.

**Comment by Daltron** [comment]
@mitulmarsonia, like I've previously mentioned, Swift 4 and Swift 3 are interchangeable. You just need to tell your post_install method to build in Swift 4.
