### ISSUE TITLE
UIFont has no member Weight

### ISSUE THREAD

**Issue by trianglepixel** [Daltron/NotificationBanner#55]
UIFont.Weight.Bold doesn't compile and needs to be UIFontWeightBold

StatusBarNotification.swift
`titleLabel!.font = UIFont.systemFont(ofSize: 12.5, weight: UIFontWeightBold)`

NotificationBanner.swift
`titleLabel!.font = UIFont.systemFont(ofSize: 17.5, weight: UIFontWeightBold)`

**Comment by Daltron** [comment]
@trianglepixel Sounds like you are on a Swift 3.x project. The latest NotificationBanner release is compiled to work with Swift 4. In your pod file, make sure your NotificationBanner pod looks like this:

```ruby
pod 'NotificationBannerSwift', '~> 1.4.4'
```

**Comment by trianglepixel** [comment]
@Daltron I had my compiler set to swift 4 and I had updated my pod the pod then re upgraded and it seems to be working now. Thanks.
