### ISSUE TITLE
Banner shows under status bar

### ISSUE THREAD

**Issue by trianglepixel** [Daltron/NotificationBanner#56]
Both NotificationBanner & StatusBarNotificationBanner show underneath status bar.

**Comment by trianglepixel** [comment]
```swift
if let parentViewController = parentViewController {
                parentViewController.view.addSubview(self)
                if statusBarShouldBeShown() {
                    appWindow.windowLevel = UIWindowLevelStatusBar + 1
                }
            } else {
                appWindow.addSubview(self)
                if statusBarShouldBeShown() && !(parentViewController == nil && bannerPosition == .top) {
                    appWindow.windowLevel = UIWindowLevelStatusBar + 1
                } else {
                    appWindow.windowLevel = UIWindowLevelStatusBar + 1
                }
            }
```

I changed the above to

```swift
if let parentViewController = parentViewController {
                parentViewController.view.addSubview(self)
                if statusBarShouldBeShown() {
                    appWindow.windowLevel = UIWindowLevelNormal
                }
            } else {
                appWindow.addSubview(self)
                if statusBarShouldBeShown() && !(parentViewController == nil && bannerPosition == .top) {
                    appWindow.windowLevel = UIWindowLevelNormal
                } else {
                    appWindow.windowLevel = UIWindowLevelStatusBar + 1
                }
            }
```

and now its on top, but I'm not sure if thats correct.

**Comment by Daltron** [comment]
Hi @trianglepixel! 😄 There is no need to change the code for what you are wanting to do. As the README states:

**By default, each banner will be displayed on the main application window. If you are wanting to show a banner below a navigation bar, simply show on the view controller that is within the navigation system:** 
```swift
banner.show(on: viewController)
```

So what you need to do is forgo the `on` parameter and your banner will show above the navigation bar 👍

**Comment by trianglepixel** [comment]
@Daltron Yes I see the issue now. Thanks.

**Comment by fukemy** [comment]
hi @Daltron, i set banner show on my topVC then it below navigation, not under, can u help?
![Screen Shot 2021-02-04 at 13 39 12](https://user-images.githubusercontent.com/8202437/106854730-6359a100-66ee-11eb-86d2-e9d37b88d5cc.png)
