### ISSUE TITLE
Compile error for release 1.4.4 on Xcode 9 and Swift 3.2

### ISSUE THREAD

**Issue by mohsenasm** [Daltron/NotificationBanner#57]
Compile error for release 1.4.4 on Xcode 9 and Swift 3.2:
`/NotificationBanner/Classes/StatusBarNotificationBanner.swift:30:12: Use of unresolved identifier 'NotificationBannerUtilities'`

<img width="1131" alt="screen shot 2017-09-27 at 10 03 13 am" src="https://user-images.githubusercontent.com/9164422/30899239-f6a89c62-a36b-11e7-9f68-5233ba65372e.png">

**Comment by mohsenasm** [comment]
Release 1.4.2 seems to work though.

**Comment by Daltron** [comment]
Hi @mohsenasm! 😄 I'm not experienced with Carthage. Any chance you can take a look and fix this problem? It just looks like the  `NotificationBannerUtilities` class isn't added to the list of sources to be compiled.

**Comment by Daltron** [comment]
Fixed by #60
