### ISSUE TITLE
iOS 9?

### ISSUE THREAD

**Issue by RtzX** [Daltron/NotificationBanner#6]
If I used on iOS 8 now, ok?Whether to support iOS 8?

**Comment by Daltron** [comment]
Hi @RtzX! 😄 Apple recommends only supporting the latest two iOS versions which would be iOS 9 and iOS 10. With iOS 11 soon on the way, iOS 9 will start to phase out as iOS users tend to adopt new versions very heavily.

**Comment by RtzX** [comment]
oh.I know. Thank you
