### ISSUE TITLE
toolBar view hides when banner appears

### ISSUE THREAD

**Issue by pselok** [Daltron/NotificationBanner#61]
Hello, awesome library!
I have a problem: when keyboard with toolbar is active and banner appears, toolbar disappears until banner dismissed. Sometimes when i type something and banner appears again toolbar does not disappears. I do simple banner.show() so banner displays on main app window. If i show banner on my tabbarcontroller everything is fine except one thing - banner shows under status bar.
![img_0640](https://user-images.githubusercontent.com/16443790/31055588-b9f86e54-a6cd-11e7-898f-8f406413ae3d.png)
![img_0642](https://user-images.githubusercontent.com/16443790/31055589-bd6c6a72-a6cd-11e7-917c-583c566732c0.png)

**Comment by Daltron** [comment]
Hi @pselok! 😄 I know exactly what you are talking about as I had this scenario happen with one of the projects I actively work on. Unfortunately, there was not an elegant solution to place inside NotificationBanner directly, so I had to do something custom in my application in order to handle this scenario. I was using an inputAccessoryView on the keyboard instead of a toolbar, so I hope this solution will work.

```swift
NotificationCenter.default.addObserver(self,
                                               selector: #selector(onNotificationBannerWillAppear),
                                               name: NotificationBanner.BannerWillAppear,
                                               object: nil)

@objc private dynamic func onNotificationBannerWillAppear(notification: Notification) {
        // NotificationBanner uses UIWindowLevelStatusBar + 1 when it shows banners
        window?.windowLevel = UIWindowLevelStatusBar + 2
}
```

**Comment by pselok** [comment]
Exactly! i'm using some new library for my chat and have the same thing in my chat controller. Seems like your solution does not work for me :(
    `let window = UIApplication.shared.delegate?.window!` - right?
I do receive a notification but `window?.windowLevel = UIWindowLevelStatusBar + 2` does not work

**Comment by pselok** [comment]
Ah it's about when i do `banner.show(on: tabBarController) `?

**Comment by Daltron** [comment]
@pselok So you don't want to change the main UIApplication's window, you want to change the window the keyboard view is actually on. I'm not sure off the top of of my head if your able to access the window from a UIToolbar object though. Is this a project you are comfortable with sending to me? If so, I should be able to tell you relatively quickly if its possible with public API's.

**Comment by pselok** [comment]
Thank you so much, it solved! 
i did `messageInputBar.window?.windowLevel = UIWindowLevelStatusBar + 2`

**Comment by Daltron** [comment]
@pselok Awesome! Glad to hear! 👍

**Comment by fukemy** [comment]
hi @pselok , i facing same problem, did u used "https://github.com/nathantannar4/InputBarAccessoryView"? I tried to make 
```
messageInputBar.window?.windowLevel = UIWindowLevelStatusBar + 2
```

But it's seem not working, when notification show the messageInputBar disappear
