### ISSUE TITLE
Wrong version of Snapkit

### ISSUE THREAD

**Issue by mateg** [Daltron/NotificationBanner#63]
Installed the pod to my project (written in Swift 4) and it won't work because 'NotificationBanner' uses Snapkit 3.2. Snapkit 4.0 is required for Swift 4 (see https://github.com/SnapKit/SnapKit). 

Please fix asap and thanks for an amazing pod otherwise, super excited to use it.

**Comment by Daltron** [comment]
Hi @mateg! 😄 Can you show me your podfile please? The latest version of NotificationBanner is Swift 4 compatible so this is definitely something on your end. However, I'd be more than happy to help you figure it out!

**Comment by mateg** [comment]
Hello Daltron, I appreciate that very much. 
I followed the install instructions but it seems like the pod installs the wrong version of SnapKit for me. I'm unable to build the project, see this image ->
![image](https://user-images.githubusercontent.com/17149695/31315324-976c6f9a-ac16-11e7-9770-d3dc46dfc579.png)

My podfile:
`
platform :ios, '9.0'
use_frameworks!

target 'Sverigespelet' do

    pod 'SwiftShareBubbles'
    pod 'EggRating'
    pod 'QuickTableViewController', '~> 0.5.0'
    pod 'Pastel'
    pod 'NotificationBannerSwift', '~> 1.4.5'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'

end
`

I dug into the example project and found in the 'podfile.lock' that is uses the **correct version, Snapkit 4.0** and therefore it works. I  tried to update my podfile.lock to 'SnapKit (~> 4.0)' (so it was identical to the example project) but then the terminal prints out this 

"`SnapKit (~> 3.2)` required by `NotificationBannerSwift (1.4.5)`" (which isn't compatible with Swift 4).
![image](https://user-images.githubusercontent.com/17149695/31315349-47a281c4-ac17-11e7-87a3-83adbc110726.png)

What should I do? Thank you for your help.

**Comment by yoshisuga** [comment]
Seeing this same issue as well - i think the pod just needs to be updated to specify SnapKit 4.0.

This looks like a neat library, looking forward to it!

**Comment by Daltron** [comment]
@mateg Looks like your problem is that your pointing to the wrong version. 😄 Swift4 support was introduced in the [v1.5.0](https://github.com/Daltron/NotificationBanner/releases/tag/1.4.1) release.

**Comment by Daltron** [comment]
@yoshisuga The pod does specify to use SnapKit 4.0 and I've upgraded multiple Swift 3 projects that used NotificationBanner to Swift 4 with no problems. What is the issue you are seeing?

**Comment by yoshisuga** [comment]
Ah! If I specified version 1.5.0 in my Podfile, it pulled SnapKit 4.0 and it looks like all is well now.  Thanks!

**Comment by mateg** [comment]
Thank you! That was it, great work! I'll let you know if I publish an app using it! :)

**Comment by Daltron** [comment]
@yoshisuga @mateg Glad to hear. Enjoy! 🎉
