### ISSUE TITLE
iPhone X StatusBarNotificationBanner size

### ISSUE THREAD

**Issue by magonicolas** [Daltron/NotificationBanner#67]
Hi guys, im seeing a very weird size for status message on iPhone X, I attach an image, Would this be solved? or any hint on how Can I make it smaller, because is way to big for a status message. [iPhone x Image](https://www.dropbox.com/s/qbeqtl4bjy28m8u/Screen%20Shot%202017-10-23%20at%203.16.58%20PM.png?dl=0)

**Comment by Daltron** [comment]
Hi @magonicolas! 😄 What you are seeing is exactly the intended behavior. If it were to be any smaller, then part of the navigation bar and possibly part of the navigation bar title text would be showing and that would look very bad in my opinion. If you are really sold on changing it, then you are more than welcome to create a fork. You would want to take a look at the `bannerHeight` property inside the `StatusBarNotificationBanner` class and provide your own custom implementation.
