### ISSUE TITLE
Status bar visible through the notification

### ISSUE THREAD

**Issue by firvorski** [Daltron/NotificationBanner#71]
Is this due to my config or something else. I can't work it out. It happens most of the time, not 100% of the time but still very often.

My code is quite basic
`            self.notificationBanner = NotificationBanner(title: title, subtitle: subtitle, style: .warning, colors: CustomBannersColors())
self.notificationBanner!.show()`

![simulator screen shot - iphone 8 - 2017-11-15 at 18 50 35](https://user-images.githubusercontent.com/5808204/32854259-f87444a6-ca35-11e7-9c56-eabb3c2e3b1c.png)

**Comment by Daltron** [comment]
Hi @firvorski! 😄 Can you give me a little bit more information please? Where are you calling the `show()` function at in your code? What version of iOS is your simulator/device running? I think if I have a little bit more information, I might be able to help you 👍

**Comment by JoniVR** [comment]
@firvorski On a side note, I would use a [switch](https://developer.apple.com/ios/human-interface-guidelines/controls/switches/) for your iCloud enable/disable option. 
The way it is currently implemented is wrong from a UI/UX standpoint and very confusing to users.

Just thought I should throw it out there 😜
Have a nice day everyone 😊

**Comment by Daltron** [comment]
@firvorski I have a feeling you are calling the show `show()` method in viewDidLoad(). If so, move it to the `viewWillAppear` or `viewWillDisappear` and I can guarantee it will work as expected :)

**Comment by firvorski** [comment]
@Daltron thank you so much for the quick response.

I am actually calling it from a callback (!) of the aforementioned switch. So, from a background thread but I make sure the actual call is on the main thread.

```
 Utils.runOnMainThreadAsync {
self.show("Unable to connect to iCloud:", subtitle: error?.localizedDescription)
}
```
```
func show(_ title: String, subtitle :String? = nil) { 
            if let _ = self.notificationBanner {
                self.notificationBanner?.dismiss()
            }
            self.notificationBanner = NotificationBanner(title: title, subtitle: subtitle, style: .warning, colors: CustomBannersColors())
            self.notificationBanner!.show()
    }
```

Xcode 9.1
Simulator 11.1 iPhone 8

**Comment by firvorski** [comment]
@JoniVR thank you very much for pointing that out. I wasn't aware that I was going against the guidelines so it's good to be aware of that.

**Comment by Daltron** [comment]
@firvorski It sounds like your calling `dismiss()` and `show()` too close together. I would call `dismiss()` first and then listen for the `notificationBannerDidDisappear(_ banner: BaseNotificationBanner)` delegate method to happen before calling `show()` on the next banner you are wanting to present.

**Comment by firvorski** [comment]
@Daltron yep that was it. Now I show it after notificationBannerDidDisappear with a small delay and it works perfectly. Thank you very much!

**Comment by Daltron** [comment]
@firvorski Glad to hear it worked!
