### ISSUE TITLE
StatusBarNotificationBanner iPhoneX height is extra big by default

### ISSUE THREAD

**Issue by btelintelo** [Daltron/NotificationBanner#79]
Can we make it come down a little to avoid the notch but not so far down that is a big banner?  For example, a height of 50px looks great, but the current height is 88px and is massive compared to the 20px height on all other devices.  For now I can set a custom height on iPhone x, but it would be nicer to make this smaller by default.

**Comment by Daltron** [comment]
Hi @btelintelo! 😄 Could you send me a picture of what a banner looks like at 50px please? I tried numerous different sizes and came to the conclusion that extending down to the end of the navigation bar looked best.

**Comment by HackShitUp** [comment]
@btelintelo @Daltron I'd suggest the banner appears below the device's status bar if it's an iPhone X. Like so:
``` swift
       // Determine if the device is an iPhone X.
        if UIScreen.main.nativeBounds.height == 2436 {
            banner.frame = CGRect(x: 0, y: UIApplication.shared.statusBarFrame.maxY,
                                  width: UIScreen.main.bounds.width, height: 20.00)
        } else {
            banner.frame = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 20.00)
        }
```
Is there a mutable frame property before displaying the banner?

**Comment by btelintelo** [comment]
Here is 50px. but I'm sure there is a better way to calculate it.

![screen shot 2018-01-08 at 10 27 07 am](https://user-images.githubusercontent.com/3678777/34677613-b3b5e880-f45e-11e7-97af-f24209648f2d.png)

**Comment by Daltron** [comment]
@HackShitUp No there is not currently a mutable frame property. @btelintelo Can you show a picture with the entire navigation bar in the picture? One of the big reasons I didn't do this was because then your cutting off part of the navigation title.

**Comment by btelintelo** [comment]
Yep, it covers part of the nav bar. But not the title or buttons.  I see why you wouldn't want this.  However, in our case, we want to keep the no network connection message constantly.  Which then covers the entire nav bar!  Another option is the bottom of screen....

**Comment by Daltron** [comment]
@btelintelo After further thinking, I think your completely right and the default height should be 50px. I have made this the standard implementation in v1.5.4 release. Simply run `pod update NotificationBannerSwift` and you should be good to go! 👍

**Comment by HackShitUp** [comment]
@btelintelo I also don't want the message bar to appear over the status bar for the iPhone X as well. 
@Daltron I just updated to v1.5.4 and the 50px height makes it less intrusive. Is it possible if you could set up an offset variable from the top of the status bar like this framework does?
https://github.com/SwiftKickMobile/SwiftMessages

**Comment by Daltron** [comment]
@HackShitUp This may be something I'll consider in the future, but as of right now, I do not plan on adding an offset property.
