### ISSUE TITLE
Some features..

### ISSUE THREAD

**Issue by JoniVR** [Daltron/NotificationBanner#8]
Hi,
I'm not really sure how I can add a "feature request" label to an issue, but anyways.
First of all, I really like this, it's really easy to use and very clean UI wise, great work!! 

Had a couple of things in mind that would be nice additions:
- the option to disable new banners when a banner is currently active. 
- the option to easily set how long a banner is shown, and to be able to check programmatically if a banner is currently being displayed. 

I would help out, but I'm currently way too busy with various projects and lots of schoolwork so I don't really have the time for it atm..

Anyways, just some things that came to my mind for possible features, thanks again! 😁

**Comment by Daltron** [comment]
Hi @JoniVR! 😄 Thanks for the kind remarks. I'm glad to hear you like it and think it is easy to use! Only I can add the feature request label to an issue so my apologies for that. I will update the README so others are not confused. Regarding your feature requests:

1. I'm not entirely sure what you mean by this one. If you could give some further explanation, that would be great!
2. Great idea! I'll include this with the next release!

Thanks! 😄

**Comment by JoniVR** [comment]
Hello @Daltron,

I'll give you an example to explain what I mean with the first point:

I have a collectionview in the setup process for my application where the user needs to select some items he/she likes, I used your library to show a notification when they try to tap the "done" button without first selecting something, the thing is, if they keep tapping "done" without selecting something, it will just keep queuing new notifications, even after the user stops pressing them. So it would be nice to be able to check if a notification is active and when it is to not queue them up.

Hope this helps, have a great day :)

**Comment by Daltron** [comment]
@JoniVR thanks for explaining, I understand your desired behavior! However, I think this functionality could be achieved by adding only the 2nd bullet point you mentioned. If you know wether or not the banner is being displayed, then you can determine wether or not to display another one (if desired). How does that sound? 😄

**Comment by JoniVR** [comment]
Yes haha now that I read it again I see that too :)
