### ISSUE TITLE
Status bar is hidden for a split second while banner is dismissing

### ISSUE THREAD

**Issue by trentjmorris** [Daltron/NotificationBanner#80]
Thank you so much for all the time you've spent developing this. It really is the best option out there for ease of use, simplicity, and performance.

I'm just curious if there is a way to change how the status bar is shown/hidden when displaying a `StatusBarNotificationBanner`. The banner displays just fine; sliding in to cover the status bar. However, after the delay is over and the banner begins to recede, the status bar is hidden until the full exit animation is complete at which time is flicks back on. This results in a rather abrupt visual.

What I am looking for:

I'd like the banner to 'slide' up and away revealing the status bar as if the banner was merely covering it up. I feel this would look more aesthetically pleasing for the user.

I tried to look through the code and attempted to alter some of the open variables/methods but to no avail. Any help/advice you could give would be extremely appreciated!

Cheers!

**Comment by Daltron** [comment]
Hi @trentjmorris! 😄 First off, thanks for the kind words! Regarding your issue, I know exactly what you are talking about. I currently haven't found a way to actually put the notification banners about the actual status bar. Instead, the status bar is hidden and then unhidden at the appropriate times which is causing the "flick" as you mentioned. As of right now, I do not plan on doing anything different until I have more time to investigate the issue.

Thanks!

**Comment by deaconudanandrei** [comment]
Might i suggest making the alpha of the Status Bar text to 0 when the notification is visible with a simple animation, and then back to 1 when the notification was dismissed.

With an extension such as this:

    extension UIApplication {
        var statusBarView: UIView? {
            return value(forKey: "statusBar") as? UIView
        }
        
        func changeStatusBar(alpha: CGFloat) {
            statusBarView?.alpha = alpha
        }
        
        func hideStatusBar() {
            UIView.animate(withDuration: 0.3) {
                self.statusBarView?.alpha = 0
            }
        }
        
        func showStatusBar() {
            UIView.animate(withDuration: 0.3) {
                self.statusBarView?.alpha = 1
            }
        }
    }

**Comment by Daltron** [comment]
@deaconudanandrei Thanks for the input but the `statusBarView` that you are talking about isn't the actual system status bar view. It's just a placeholder view that takes up the space of the status bar so this solution wouldn't work unfortunately.

**Comment by Daltron** [comment]
Going to close this issue for now as there doesn't seem to be a clear workaround at the moment.
