### ISSUE TITLE
Allow changing banner default NotificationBannerQueue

### ISSUE THREAD

**Issue by t4ec** [Daltron/NotificationBanner#82]
Hello,

I am working on an application which has several independent UIViewControllers (basically nested under TabBarVC), each of them can make API requests, each can fail due to connection issues, etc. 

At the moment, if I run `banner.show(on: VC)` from different VCs common queue still waits for the previous banner shown on other VC to disappear or be dismissed before showing a new banner. Which breaks the user experience.

As I can see, at the moment the `bannerQueue` property is private, immutable and cannot be overridden:

`private let bannerQueue: NotificationBannerQueue = NotificationBannerQueue.default`

It would be great to have the ability to set separate NotificationBannerQueue for each controller and be able to run

`banner.show(on: VC, onQueue: ThisVeryVCQueue)`

Please let me know If there is a workaround.

Thank you in advance.

**Comment by Daltron** [comment]
Hi @t4ec! 😄 I really really like this idea. I'm going to add a feature request label to this issue and see if I can implement what you are looking for when I have some free time. 👍

**Comment by Daltron** [comment]
@t4ec This is now a feature in the [v1.6.0](https://github.com/Daltron/NotificationBanner/releases/tag/1.6.0) release. I'd love to hear some feedback after you use it! Thanks again for the feature request! 👍 👍 👍

**Comment by t4ec** [comment]
@Daltron Wow, that was really fast. As far as I can see it works flawlessly in context of my use-case.

Thanks a lot!

**Comment by Daltron** [comment]
@t4ec No problem at all. Thanks for such a great idea. I can see a bunch of scenarios that greatly benefit from being able to manage your own banner queues.
