### ISSUE TITLE
rotation not supported with custom views

### ISSUE THREAD

**Issue by valexa** [Daltron/NotificationBanner#83]
When setting a banner to bottom with a custom view and rotating devices from landscape to portrait the banner now is in the middle of the screen 

            banner = NotificationBanner(customView: view)
            banner.autoDismiss = false
            banner.show(bannerPosition: .bottom)

**Comment by Daltron** [comment]
@valexa Thanks for bringing this to my attention. 👍  It didn't appear to be an issue with custom views, but the actual `.bottom` banner position as a whole.  This is now fixed in the [v1.6.1](https://github.com/Daltron/NotificationBanner/releases/tag/1.6.1) release. 🎉
