### ISSUE TITLE
Adding NotificationBanner via Carthage

### ISSUE THREAD

**Issue by Ronaldoh1** [Daltron/NotificationBanner#85]
Hi, 

I'm trying to add your framework via Carthage, but it's taking forever. It doesn't get pass the
 *** Fetching NotificationBanner

part. 

Not sure if its this or 

*** Fetching MarqueeLabel  d

dependency. 

Any workarounds?

**Comment by Ronaldoh1** [comment]
I keep getting 

Dependency "NotificationBanner" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Daltron/NotificationBanner/issues/new

**Comment by Ronaldoh1** [comment]
adding github "Daltron/NotificationBanner" "master" to cart file didn't work ... maybe it's not the right path?

**Comment by Daltron** [comment]
Hi @Ronaldoh1! 😄 Unfortunately, I can not provide much help when it comes to Carthage related questions as I have zero experience with it and wasn't the one who added support for it in this library. @Dschee, would you be able to provide some help on why this might be happening?

**Comment by Dschee** [comment]
@Ronaldoh1 I just tested this by creating an empty Folder and adding a `Cartfile` with the following content:

```
github "Daltron/NotificationBanner"
```

Then I ran `carthage update --platform ios --cache-builds` on the command line and here's the complete output:

```
$ carthage update --platform ios --cache-builds
*** Fetching NotificationBanner
*** Fetching SnapKit
*** Fetching MarqueeLabel
*** Checking out SnapKit at "3.2.0"
*** Checking out MarqueeLabel at "3.1.4"
*** Checking out NotificationBanner at "1.6.1"
*** No cache found for MarqueeLabel, building with all downstream dependencies
*** No cache found for SnapKit, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/0n/_ylkyb013fqg0dxk_h0l4jmw0000gp/T/carthage-xcodebuild.4AB0PJ.log
*** Building scheme "MarqueeLabel" in MarqueeLabel.xcworkspace
*** Building scheme "MarqueeLabelSwift" in MarqueeLabel.xcworkspace
*** Building scheme "SnapKit" in SnapKit.xcworkspace
*** Building scheme "NotificationBanner" in NotificationBanner.xcodeproj
```

As you can see it works perfectly fine with the latest version of NotificationBanner. Therefore I suggest you first check that you have the latest version of Carthage and Xcode installed (`brew upgrade carthage` and Xcode 9.3). Also a system restart is always something to consider. If it still doesn't work, I suggest you file a bug report on https://github.com/Carthage/Carthage/issues

**Comment by Daltron** [comment]
@Dschee Thanks for confirming this 👍 Going to close this issue for now.

**Comment by Ronaldoh1** [comment]
hi guys ... I finally got around to try it. The reason why this is not working is because 

Could not pick a version for github "SnapKit/SnapKit", due to mutually incompatible requirements:
	~> 4.0.0
	~> 3.2.0 (github "Daltron/NotificationBanner")

My project uses snap kit and we're already using 4.0.0 is it possible that this might the reason why it keeps hanging when I run `carthage update --platform iOS --no-use-binaries`

if you run `carthage update --platform iOS --no-use-binaries` on a new project it will work like a charm. But if snap kit is already there, then it hangs and never completes the checkout.

**Comment by Ronaldoh1** [comment]
yeah I updated the version on my fork and it worked
