### ISSUE TITLE
Cocoapod issue overriding BannerColors

### ISSUE THREAD

**Issue by thebrandontyler** [Daltron/NotificationBanner#86]
When I try to create a custom color for a banner using cocoapods, I get a "Cannot inherit from non-open class 'BannerColors' outside of its defining module."

It seems like if Notification Banner is added as a pod, then the class and method instance must be open instead of public in order to override it since it is not in the same project/module.  I checked out your example and the BannerColors.swift is in the example project (not a pod), so public seems to work fine.

I can change this myself since the files are visible in the pod, but when the pod has updates, it may revert back to public and cause errors.

**Comment by quver** [comment]
```
class CustomBannerColors: BannerColorsProtocol {

    internal override func color(for style: BannerStyle) -> UIColor {
        switch style {
            case .danger:   // Your custom .danger color
            case .info:     // Your custom .info color
            case .none:     // Your custom .none color
            case .success:  // Your custom .success color
            case .warning:  // Your custom .warning color
        }
    }

}
```

you have to conform to protocol instead of inherit

**Comment by thebrandontyler** [comment]
Thanks for the feedback. 
I tried that too and received this error: Method does not override any method from its superclass.
If I remove the override keyword, it builds and works!
Thanks again.

**Comment by quver** [comment]
I updated my answer, I will create pull request because I copy&paste this code from documentation
