### ISSUE TITLE
Making the left image view round

### ISSUE THREAD

**Issue by kelvinfok** [Daltron/NotificationBanner#88]
Hi, is there a way to make the image view round?

**Comment by Daltron** [comment]
Hi @kelvinfok! 😄 You definitely can.  You just need to set the `cornerRadius` property on your view's layer to half the height of your view. The left and right views have 10px of padding from the top and the bottom so if you do this: 

```swift
yourView.layer.cornerRadius = (banner.bannerHeight - 20) / 2
```

it should be exactly what your looking for!
