### ISSUE TITLE
Banner crashing on dismiss

### ISSUE THREAD

**Issue by dvluong** [Daltron/NotificationBanner#90]
` 
        UIView.animate(withDuration: 0.5, animations: {
            self.frame = self.bannerPositionFrame.startFrame
        }) { (completed) in
            self.removeFromSuperview()
            self.isDisplaying = false
        }`

Getting a crash at this line 'self.frame = self.bannerPositionFrame.startFrame' stating that it is nil. Any idea why this may be happening?

**Comment by Daltron** [comment]
Hi @dvluong! 😄 #93 Fixed this and the `1.6.2` CocoaPods release has this fixed. Thanks!
