### ISSUE TITLE
Upgrade SnapKit to 4.0.0

### ISSUE THREAD

**Issue by sadiq81** [Daltron/NotificationBanner#91]
I assumed a lot of us have moved on the using snapkit vs 4

So please upgrade

`github "SnapKit/SnapKit" ~> 4.0.0`

**Comment by Daltron** [comment]
Hi @sadiq81 #89 updated SnapKit to 4.0 for Carthage. If you are using CocoaPods, then it should already be using SnapKit 4.0. Thanks! 👍
