### ISSUE TITLE
Banner cuts off on top on iphone X

### ISSUE THREAD

**Issue by prati691** [Daltron/NotificationBanner#94]
Please fix this ASAP

**Comment by xbauquet** [comment]
Can you give a little bit more context please.
For example which banner ... it would help fixing the problem.

**Comment by prati691** [comment]
I am using top banner. It looks fine on screenshot but when running on actual device, It comes behind the status bar.

**Comment by xbauquet** [comment]
Can you take a screenshot with your iPhone X ? 
Which version of the library are you using ?

**Comment by Daltron** [comment]
@prati691 as @xbauquet has mentioned, a screenshot would be greatly appreciated. Stating to fix something ASAP without any other information is usually not a great way to get a developer's attention 😄

**Comment by StanislavK** [comment]
@prati691 Make sure the navigation bar is not translucent (i.e. in IB, "Translucent" of Navigation Bar is not selected for the embedding UINavigationBar), or add (in your code) `edgesForExtendedLayout = UIRectEdge()` to your VC init.
