### ISSUE TITLE
Dismiss the Notification before the animation of showing causes it not to be dismissed

### ISSUE THREAD

**Issue by luksfarris** [Daltron/NotificationBanner#98]
Currently you use the boolean `isShowing` to control this, but it's only set after the 0.5sec animation runs. If someone try to dismiss it before 0.5sec it's not dismissed.

Moving `self.isDisplaying = true` to outside the animation completion callback fixes this, and makes sense. Do you agree? Can I help by creating a pull request?

**Comment by Daltron** [comment]
Hi @luksfarris! 😄 Sorry for the delayed response. Feel free to open a full request!

**Comment by luksfarris** [comment]
It's opened 😊  thanks

**Comment by Daltron** [comment]
@luksfarris After further thinking and seeing your pull request, I'm unsure what it solves. The `isDisplaying` property should not be set to true until it is fully displayed. What issue are you running into exactly? Thanks!

**Comment by sushant40** [comment]
Hi, what a small world... I am seeing this issue too.

Though what I'd much rather prefer is the ability to instantly 'swap' out a status bar notification. IE change a .success to a .warning with different text without dismissing it.

**Comment by sushant40** [comment]
for the sake of this issue. I cant speak for the pull request. Basically we should be able to dismiss a notification within 0.5s as this could be something totally out of our control... EG... because a "warning you have no network" alert is dismissed because now there is network.

**Comment by jlichti** [comment]
I'm seeing an issue where I add a autoDismiss = false banner to the queue and then if I dismiss it before it was ever shown the banner will show forever.


For a quick workaround I added a check for isDisplaying when trying to dismiss and if not then I set to auto dismiss.
